// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
 class Bindings_3 extends Bindings_2 {

    public static int UINT_LEAST8_MAX() {
        return (int)255L;
    }
    public static int UINT_LEAST16_MAX() {
        return (int)65535L;
    }
    public static int UINT_LEAST32_MAX() {
        return (int)4294967295L;
    }
    public static long UINT_LEAST64_MAX() {
        return -1L;
    }
    public static int INT_FAST8_MIN() {
        return (int)-128L;
    }
    public static int INT_FAST16_MIN() {
        return (int)-32768L;
    }
    public static int INT_FAST32_MIN() {
        return (int)-2147483648L;
    }
    public static long INT_FAST64_MIN() {
        return -9223372036854775808L;
    }
    public static int INT_FAST8_MAX() {
        return (int)127L;
    }
    public static int INT_FAST16_MAX() {
        return (int)32767L;
    }
    public static int INT_FAST32_MAX() {
        return (int)2147483647L;
    }
    public static long INT_FAST64_MAX() {
        return 9223372036854775807L;
    }
    public static int UINT_FAST8_MAX() {
        return (int)255L;
    }
    public static int UINT_FAST16_MAX() {
        return (int)65535L;
    }
    public static int UINT_FAST32_MAX() {
        return (int)4294967295L;
    }
    public static long UINT_FAST64_MAX() {
        return -1L;
    }
    public static long INTPTR_MAX() {
        return 9223372036854775807L;
    }
    public static long INTPTR_MIN() {
        return -9223372036854775808L;
    }
    public static long UINTPTR_MAX() {
        return -1L;
    }
    public static long INTMAX_MAX() {
        return 9223372036854775807L;
    }
    public static long UINTMAX_MAX() {
        return -1L;
    }
    public static long INTMAX_MIN() {
        return -9223372036854775808L;
    }
    public static long PTRDIFF_MIN() {
        return -9223372036854775808L;
    }
    public static long PTRDIFF_MAX() {
        return 9223372036854775807L;
    }
    public static long SIZE_MAX() {
        return -1L;
    }
    public static long RSIZE_MAX() {
        return 9223372036854775807L;
    }
    public static int WCHAR_MAX() {
        return (int)2147483647L;
    }
    public static int WCHAR_MIN() {
        return (int)-2147483648L;
    }
    public static int WINT_MIN() {
        return (int)-2147483648L;
    }
    public static int WINT_MAX() {
        return (int)2147483647L;
    }
    public static int SIG_ATOMIC_MIN() {
        return (int)-2147483648L;
    }
    public static int SIG_ATOMIC_MAX() {
        return (int)2147483647L;
    }
    public static int __DARWIN_WCHAR_MAX() {
        return (int)2147483647L;
    }
    public static int __DARWIN_WCHAR_MIN() {
        return (int)-2147483648L;
    }
    public static int __DARWIN_WEOF() {
        return (int)-1L;
    }
    public static MemoryAddress NULL() {
        return constants$360.NULL$ADDR;
    }
    public static MemorySegment __PRI_8_LENGTH_MODIFIER__() {
        return constants$360.__PRI_8_LENGTH_MODIFIER__$SEGMENT;
    }
    public static MemorySegment __PRI_64_LENGTH_MODIFIER__() {
        return constants$360.__PRI_64_LENGTH_MODIFIER__$SEGMENT;
    }
    public static MemorySegment __SCN_64_LENGTH_MODIFIER__() {
        return constants$360.__SCN_64_LENGTH_MODIFIER__$SEGMENT;
    }
    public static MemorySegment __PRI_MAX_LENGTH_MODIFIER__() {
        return constants$360.__PRI_MAX_LENGTH_MODIFIER__$SEGMENT;
    }
    public static MemorySegment __SCN_MAX_LENGTH_MODIFIER__() {
        return constants$360.__SCN_MAX_LENGTH_MODIFIER__$SEGMENT;
    }
    public static MemorySegment PRId8() {
        return constants$361.PRId8$SEGMENT;
    }
    public static MemorySegment PRIi8() {
        return constants$361.PRIi8$SEGMENT;
    }
    public static MemorySegment PRIo8() {
        return constants$361.PRIo8$SEGMENT;
    }
    public static MemorySegment PRIu8() {
        return constants$361.PRIu8$SEGMENT;
    }
    public static MemorySegment PRIx8() {
        return constants$361.PRIx8$SEGMENT;
    }
    public static MemorySegment PRIX8() {
        return constants$361.PRIX8$SEGMENT;
    }
    public static MemorySegment PRId16() {
        return constants$362.PRId16$SEGMENT;
    }
    public static MemorySegment PRIi16() {
        return constants$362.PRIi16$SEGMENT;
    }
    public static MemorySegment PRIo16() {
        return constants$362.PRIo16$SEGMENT;
    }
    public static MemorySegment PRIu16() {
        return constants$362.PRIu16$SEGMENT;
    }
    public static MemorySegment PRIx16() {
        return constants$362.PRIx16$SEGMENT;
    }
    public static MemorySegment PRIX16() {
        return constants$362.PRIX16$SEGMENT;
    }
    public static MemorySegment PRId32() {
        return constants$363.PRId32$SEGMENT;
    }
    public static MemorySegment PRIi32() {
        return constants$363.PRIi32$SEGMENT;
    }
    public static MemorySegment PRIo32() {
        return constants$363.PRIo32$SEGMENT;
    }
    public static MemorySegment PRIu32() {
        return constants$363.PRIu32$SEGMENT;
    }
    public static MemorySegment PRIx32() {
        return constants$363.PRIx32$SEGMENT;
    }
    public static MemorySegment PRIX32() {
        return constants$363.PRIX32$SEGMENT;
    }
    public static MemorySegment PRId64() {
        return constants$364.PRId64$SEGMENT;
    }
    public static MemorySegment PRIi64() {
        return constants$364.PRIi64$SEGMENT;
    }
    public static MemorySegment PRIo64() {
        return constants$364.PRIo64$SEGMENT;
    }
    public static MemorySegment PRIu64() {
        return constants$364.PRIu64$SEGMENT;
    }
    public static MemorySegment PRIx64() {
        return constants$364.PRIx64$SEGMENT;
    }
    public static MemorySegment PRIX64() {
        return constants$364.PRIX64$SEGMENT;
    }
    public static MemorySegment PRIdLEAST8() {
        return constants$365.PRIdLEAST8$SEGMENT;
    }
    public static MemorySegment PRIiLEAST8() {
        return constants$365.PRIiLEAST8$SEGMENT;
    }
    public static MemorySegment PRIoLEAST8() {
        return constants$365.PRIoLEAST8$SEGMENT;
    }
    public static MemorySegment PRIuLEAST8() {
        return constants$365.PRIuLEAST8$SEGMENT;
    }
    public static MemorySegment PRIxLEAST8() {
        return constants$365.PRIxLEAST8$SEGMENT;
    }
    public static MemorySegment PRIXLEAST8() {
        return constants$365.PRIXLEAST8$SEGMENT;
    }
    public static MemorySegment PRIdLEAST16() {
        return constants$366.PRIdLEAST16$SEGMENT;
    }
    public static MemorySegment PRIiLEAST16() {
        return constants$366.PRIiLEAST16$SEGMENT;
    }
    public static MemorySegment PRIoLEAST16() {
        return constants$366.PRIoLEAST16$SEGMENT;
    }
    public static MemorySegment PRIuLEAST16() {
        return constants$366.PRIuLEAST16$SEGMENT;
    }
    public static MemorySegment PRIxLEAST16() {
        return constants$366.PRIxLEAST16$SEGMENT;
    }
    public static MemorySegment PRIXLEAST16() {
        return constants$366.PRIXLEAST16$SEGMENT;
    }
    public static MemorySegment PRIdLEAST32() {
        return constants$367.PRIdLEAST32$SEGMENT;
    }
    public static MemorySegment PRIiLEAST32() {
        return constants$367.PRIiLEAST32$SEGMENT;
    }
    public static MemorySegment PRIoLEAST32() {
        return constants$367.PRIoLEAST32$SEGMENT;
    }
    public static MemorySegment PRIuLEAST32() {
        return constants$367.PRIuLEAST32$SEGMENT;
    }
    public static MemorySegment PRIxLEAST32() {
        return constants$367.PRIxLEAST32$SEGMENT;
    }
    public static MemorySegment PRIXLEAST32() {
        return constants$367.PRIXLEAST32$SEGMENT;
    }
    public static MemorySegment PRIdLEAST64() {
        return constants$368.PRIdLEAST64$SEGMENT;
    }
    public static MemorySegment PRIiLEAST64() {
        return constants$368.PRIiLEAST64$SEGMENT;
    }
    public static MemorySegment PRIoLEAST64() {
        return constants$368.PRIoLEAST64$SEGMENT;
    }
    public static MemorySegment PRIuLEAST64() {
        return constants$368.PRIuLEAST64$SEGMENT;
    }
    public static MemorySegment PRIxLEAST64() {
        return constants$368.PRIxLEAST64$SEGMENT;
    }
    public static MemorySegment PRIXLEAST64() {
        return constants$368.PRIXLEAST64$SEGMENT;
    }
    public static MemorySegment PRIdFAST8() {
        return constants$369.PRIdFAST8$SEGMENT;
    }
    public static MemorySegment PRIiFAST8() {
        return constants$369.PRIiFAST8$SEGMENT;
    }
    public static MemorySegment PRIoFAST8() {
        return constants$369.PRIoFAST8$SEGMENT;
    }
    public static MemorySegment PRIuFAST8() {
        return constants$369.PRIuFAST8$SEGMENT;
    }
    public static MemorySegment PRIxFAST8() {
        return constants$369.PRIxFAST8$SEGMENT;
    }
    public static MemorySegment PRIXFAST8() {
        return constants$369.PRIXFAST8$SEGMENT;
    }
    public static MemorySegment PRIdFAST16() {
        return constants$370.PRIdFAST16$SEGMENT;
    }
    public static MemorySegment PRIiFAST16() {
        return constants$370.PRIiFAST16$SEGMENT;
    }
    public static MemorySegment PRIoFAST16() {
        return constants$370.PRIoFAST16$SEGMENT;
    }
    public static MemorySegment PRIuFAST16() {
        return constants$370.PRIuFAST16$SEGMENT;
    }
    public static MemorySegment PRIxFAST16() {
        return constants$370.PRIxFAST16$SEGMENT;
    }
    public static MemorySegment PRIXFAST16() {
        return constants$370.PRIXFAST16$SEGMENT;
    }
    public static MemorySegment PRIdFAST32() {
        return constants$371.PRIdFAST32$SEGMENT;
    }
    public static MemorySegment PRIiFAST32() {
        return constants$371.PRIiFAST32$SEGMENT;
    }
    public static MemorySegment PRIoFAST32() {
        return constants$371.PRIoFAST32$SEGMENT;
    }
    public static MemorySegment PRIuFAST32() {
        return constants$371.PRIuFAST32$SEGMENT;
    }
    public static MemorySegment PRIxFAST32() {
        return constants$371.PRIxFAST32$SEGMENT;
    }
    public static MemorySegment PRIXFAST32() {
        return constants$371.PRIXFAST32$SEGMENT;
    }
    public static MemorySegment PRIdFAST64() {
        return constants$372.PRIdFAST64$SEGMENT;
    }
    public static MemorySegment PRIiFAST64() {
        return constants$372.PRIiFAST64$SEGMENT;
    }
    public static MemorySegment PRIoFAST64() {
        return constants$372.PRIoFAST64$SEGMENT;
    }
    public static MemorySegment PRIuFAST64() {
        return constants$372.PRIuFAST64$SEGMENT;
    }
    public static MemorySegment PRIxFAST64() {
        return constants$372.PRIxFAST64$SEGMENT;
    }
    public static MemorySegment PRIXFAST64() {
        return constants$372.PRIXFAST64$SEGMENT;
    }
    public static MemorySegment PRIdPTR() {
        return constants$373.PRIdPTR$SEGMENT;
    }
    public static MemorySegment PRIiPTR() {
        return constants$373.PRIiPTR$SEGMENT;
    }
    public static MemorySegment PRIoPTR() {
        return constants$373.PRIoPTR$SEGMENT;
    }
    public static MemorySegment PRIuPTR() {
        return constants$373.PRIuPTR$SEGMENT;
    }
    public static MemorySegment PRIxPTR() {
        return constants$373.PRIxPTR$SEGMENT;
    }
    public static MemorySegment PRIXPTR() {
        return constants$373.PRIXPTR$SEGMENT;
    }
    public static MemorySegment PRIdMAX() {
        return constants$374.PRIdMAX$SEGMENT;
    }
    public static MemorySegment PRIiMAX() {
        return constants$374.PRIiMAX$SEGMENT;
    }
    public static MemorySegment PRIoMAX() {
        return constants$374.PRIoMAX$SEGMENT;
    }
    public static MemorySegment PRIuMAX() {
        return constants$374.PRIuMAX$SEGMENT;
    }
    public static MemorySegment PRIxMAX() {
        return constants$374.PRIxMAX$SEGMENT;
    }
    public static MemorySegment PRIXMAX() {
        return constants$374.PRIXMAX$SEGMENT;
    }
    public static MemorySegment SCNd8() {
        return constants$375.SCNd8$SEGMENT;
    }
    public static MemorySegment SCNi8() {
        return constants$375.SCNi8$SEGMENT;
    }
    public static MemorySegment SCNo8() {
        return constants$375.SCNo8$SEGMENT;
    }
    public static MemorySegment SCNu8() {
        return constants$375.SCNu8$SEGMENT;
    }
    public static MemorySegment SCNx8() {
        return constants$375.SCNx8$SEGMENT;
    }
    public static MemorySegment SCNd16() {
        return constants$375.SCNd16$SEGMENT;
    }
    public static MemorySegment SCNi16() {
        return constants$376.SCNi16$SEGMENT;
    }
    public static MemorySegment SCNo16() {
        return constants$376.SCNo16$SEGMENT;
    }
    public static MemorySegment SCNu16() {
        return constants$376.SCNu16$SEGMENT;
    }
    public static MemorySegment SCNx16() {
        return constants$376.SCNx16$SEGMENT;
    }
    public static MemorySegment SCNd32() {
        return constants$376.SCNd32$SEGMENT;
    }
    public static MemorySegment SCNi32() {
        return constants$376.SCNi32$SEGMENT;
    }
    public static MemorySegment SCNo32() {
        return constants$377.SCNo32$SEGMENT;
    }
    public static MemorySegment SCNu32() {
        return constants$377.SCNu32$SEGMENT;
    }
    public static MemorySegment SCNx32() {
        return constants$377.SCNx32$SEGMENT;
    }
    public static MemorySegment SCNd64() {
        return constants$377.SCNd64$SEGMENT;
    }
    public static MemorySegment SCNi64() {
        return constants$377.SCNi64$SEGMENT;
    }
    public static MemorySegment SCNo64() {
        return constants$377.SCNo64$SEGMENT;
    }
    public static MemorySegment SCNu64() {
        return constants$378.SCNu64$SEGMENT;
    }
    public static MemorySegment SCNx64() {
        return constants$378.SCNx64$SEGMENT;
    }
    public static MemorySegment SCNdLEAST8() {
        return constants$378.SCNdLEAST8$SEGMENT;
    }
    public static MemorySegment SCNiLEAST8() {
        return constants$378.SCNiLEAST8$SEGMENT;
    }
    public static MemorySegment SCNoLEAST8() {
        return constants$378.SCNoLEAST8$SEGMENT;
    }
    public static MemorySegment SCNuLEAST8() {
        return constants$378.SCNuLEAST8$SEGMENT;
    }
    public static MemorySegment SCNxLEAST8() {
        return constants$379.SCNxLEAST8$SEGMENT;
    }
    public static MemorySegment SCNdLEAST16() {
        return constants$379.SCNdLEAST16$SEGMENT;
    }
    public static MemorySegment SCNiLEAST16() {
        return constants$379.SCNiLEAST16$SEGMENT;
    }
    public static MemorySegment SCNoLEAST16() {
        return constants$379.SCNoLEAST16$SEGMENT;
    }
    public static MemorySegment SCNuLEAST16() {
        return constants$379.SCNuLEAST16$SEGMENT;
    }
    public static MemorySegment SCNxLEAST16() {
        return constants$379.SCNxLEAST16$SEGMENT;
    }
    public static MemorySegment SCNdLEAST32() {
        return constants$380.SCNdLEAST32$SEGMENT;
    }
    public static MemorySegment SCNiLEAST32() {
        return constants$380.SCNiLEAST32$SEGMENT;
    }
    public static MemorySegment SCNoLEAST32() {
        return constants$380.SCNoLEAST32$SEGMENT;
    }
    public static MemorySegment SCNuLEAST32() {
        return constants$380.SCNuLEAST32$SEGMENT;
    }
    public static MemorySegment SCNxLEAST32() {
        return constants$380.SCNxLEAST32$SEGMENT;
    }
    public static MemorySegment SCNdLEAST64() {
        return constants$380.SCNdLEAST64$SEGMENT;
    }
    public static MemorySegment SCNiLEAST64() {
        return constants$381.SCNiLEAST64$SEGMENT;
    }
    public static MemorySegment SCNoLEAST64() {
        return constants$381.SCNoLEAST64$SEGMENT;
    }
    public static MemorySegment SCNuLEAST64() {
        return constants$381.SCNuLEAST64$SEGMENT;
    }
    public static MemorySegment SCNxLEAST64() {
        return constants$381.SCNxLEAST64$SEGMENT;
    }
    public static MemorySegment SCNdFAST8() {
        return constants$381.SCNdFAST8$SEGMENT;
    }
    public static MemorySegment SCNiFAST8() {
        return constants$381.SCNiFAST8$SEGMENT;
    }
    public static MemorySegment SCNoFAST8() {
        return constants$382.SCNoFAST8$SEGMENT;
    }
    public static MemorySegment SCNuFAST8() {
        return constants$382.SCNuFAST8$SEGMENT;
    }
    public static MemorySegment SCNxFAST8() {
        return constants$382.SCNxFAST8$SEGMENT;
    }
    public static MemorySegment SCNdFAST16() {
        return constants$382.SCNdFAST16$SEGMENT;
    }
    public static MemorySegment SCNiFAST16() {
        return constants$382.SCNiFAST16$SEGMENT;
    }
    public static MemorySegment SCNoFAST16() {
        return constants$382.SCNoFAST16$SEGMENT;
    }
    public static MemorySegment SCNuFAST16() {
        return constants$383.SCNuFAST16$SEGMENT;
    }
    public static MemorySegment SCNxFAST16() {
        return constants$383.SCNxFAST16$SEGMENT;
    }
    public static MemorySegment SCNdFAST32() {
        return constants$383.SCNdFAST32$SEGMENT;
    }
    public static MemorySegment SCNiFAST32() {
        return constants$383.SCNiFAST32$SEGMENT;
    }
    public static MemorySegment SCNoFAST32() {
        return constants$383.SCNoFAST32$SEGMENT;
    }
    public static MemorySegment SCNuFAST32() {
        return constants$383.SCNuFAST32$SEGMENT;
    }
    public static MemorySegment SCNxFAST32() {
        return constants$384.SCNxFAST32$SEGMENT;
    }
    public static MemorySegment SCNdFAST64() {
        return constants$384.SCNdFAST64$SEGMENT;
    }
    public static MemorySegment SCNiFAST64() {
        return constants$384.SCNiFAST64$SEGMENT;
    }
    public static MemorySegment SCNoFAST64() {
        return constants$384.SCNoFAST64$SEGMENT;
    }
    public static MemorySegment SCNuFAST64() {
        return constants$384.SCNuFAST64$SEGMENT;
    }
    public static MemorySegment SCNxFAST64() {
        return constants$384.SCNxFAST64$SEGMENT;
    }
    public static MemorySegment SCNdPTR() {
        return constants$385.SCNdPTR$SEGMENT;
    }
    public static MemorySegment SCNiPTR() {
        return constants$385.SCNiPTR$SEGMENT;
    }
    public static MemorySegment SCNoPTR() {
        return constants$385.SCNoPTR$SEGMENT;
    }
    public static MemorySegment SCNuPTR() {
        return constants$385.SCNuPTR$SEGMENT;
    }
    public static MemorySegment SCNxPTR() {
        return constants$385.SCNxPTR$SEGMENT;
    }
    public static MemorySegment SCNdMAX() {
        return constants$385.SCNdMAX$SEGMENT;
    }
    public static MemorySegment SCNiMAX() {
        return constants$386.SCNiMAX$SEGMENT;
    }
    public static MemorySegment SCNoMAX() {
        return constants$386.SCNoMAX$SEGMENT;
    }
    public static MemorySegment SCNuMAX() {
        return constants$386.SCNuMAX$SEGMENT;
    }
    public static MemorySegment SCNxMAX() {
        return constants$386.SCNxMAX$SEGMENT;
    }
    public static int __MAC_OS_X_VERSION_MIN_REQUIRED() {
        return (int)120000L;
    }
    public static int __MAC_OS_X_VERSION_MAX_ALLOWED() {
        return (int)110300L;
    }
    public static int __DARWIN_BYTE_ORDER() {
        return (int)1234L;
    }
    public static int LITTLE_ENDIAN() {
        return (int)1234L;
    }
    public static int BIG_ENDIAN() {
        return (int)4321L;
    }
    public static int PDP_ENDIAN() {
        return (int)3412L;
    }
    public static int BYTE_ORDER() {
        return (int)1234L;
    }
    public static long __DARWIN_NFDBITS() {
        return 32L;
    }
    public static int NBBY() {
        return (int)8L;
    }
    public static long NFDBITS() {
        return 32L;
    }
    public static int FD_SETSIZE() {
        return (int)1024L;
    }
    public static MemorySegment LLVM_DEFAULT_TARGET_TRIPLE() {
        return constants$386.LLVM_DEFAULT_TARGET_TRIPLE$SEGMENT;
    }
    public static MemorySegment LLVM_HOST_TRIPLE() {
        return constants$386.LLVM_HOST_TRIPLE$SEGMENT;
    }
    public static MemorySegment LLVM_VERSION_STRING() {
        return constants$387.LLVM_VERSION_STRING$SEGMENT;
    }
    public static MemorySegment LLVM_BLAKE3_VERSION_STRING() {
        return constants$387.LLVM_BLAKE3_VERSION_STRING$SEGMENT;
    }
    public static long LLVMDisassembler_ReferenceType_In_ARM64_ADRP() {
        return 4294967297L;
    }
    public static long LLVMDisassembler_ReferenceType_In_ARM64_ADDXri() {
        return 4294967298L;
    }
    public static long LLVMDisassembler_ReferenceType_In_ARM64_LDRXui() {
        return 4294967299L;
    }
    public static long LLVMDisassembler_ReferenceType_In_ARM64_LDRXl() {
        return 4294967300L;
    }
    public static long LLVMDisassembler_ReferenceType_In_ARM64_ADR() {
        return 4294967301L;
    }
}


