// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$303 {

    static final FunctionDescriptor LLVMAddBitTrackingDCEPass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddBitTrackingDCEPass$MH = RuntimeHelper.downcallHandle(
        "LLVMAddBitTrackingDCEPass",
        constants$303.LLVMAddBitTrackingDCEPass$FUNC
    );
    static final FunctionDescriptor LLVMAddAlignmentFromAssumptionsPass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddAlignmentFromAssumptionsPass$MH = RuntimeHelper.downcallHandle(
        "LLVMAddAlignmentFromAssumptionsPass",
        constants$303.LLVMAddAlignmentFromAssumptionsPass$FUNC
    );
    static final FunctionDescriptor LLVMAddCFGSimplificationPass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddCFGSimplificationPass$MH = RuntimeHelper.downcallHandle(
        "LLVMAddCFGSimplificationPass",
        constants$303.LLVMAddCFGSimplificationPass$FUNC
    );
    static final FunctionDescriptor LLVMAddDeadStoreEliminationPass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddDeadStoreEliminationPass$MH = RuntimeHelper.downcallHandle(
        "LLVMAddDeadStoreEliminationPass",
        constants$303.LLVMAddDeadStoreEliminationPass$FUNC
    );
    static final FunctionDescriptor LLVMAddScalarizerPass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddScalarizerPass$MH = RuntimeHelper.downcallHandle(
        "LLVMAddScalarizerPass",
        constants$303.LLVMAddScalarizerPass$FUNC
    );
    static final FunctionDescriptor LLVMAddMergedLoadStoreMotionPass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddMergedLoadStoreMotionPass$MH = RuntimeHelper.downcallHandle(
        "LLVMAddMergedLoadStoreMotionPass",
        constants$303.LLVMAddMergedLoadStoreMotionPass$FUNC
    );
}


