// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$331 {

    static final FunctionDescriptor LLVMGetComdatSelectionKind$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetComdatSelectionKind$MH = RuntimeHelper.downcallHandle(
        "LLVMGetComdatSelectionKind",
        constants$331.LLVMGetComdatSelectionKind$FUNC
    );
    static final FunctionDescriptor LLVMSetComdatSelectionKind$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMSetComdatSelectionKind$MH = RuntimeHelper.downcallHandle(
        "LLVMSetComdatSelectionKind",
        constants$331.LLVMSetComdatSelectionKind$FUNC
    );
    static final FunctionDescriptor LLVMParseIRInContext$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMParseIRInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMParseIRInContext",
        constants$331.LLVMParseIRInContext$FUNC
    );
    static final FunctionDescriptor LLVMCreateDisasm$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMCreateDisasm$MH = RuntimeHelper.downcallHandle(
        "LLVMCreateDisasm",
        constants$331.LLVMCreateDisasm$FUNC
    );
    static final FunctionDescriptor LLVMCreateDisasmCPU$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMCreateDisasmCPU$MH = RuntimeHelper.downcallHandle(
        "LLVMCreateDisasmCPU",
        constants$331.LLVMCreateDisasmCPU$FUNC
    );
    static final FunctionDescriptor LLVMCreateDisasmCPUFeatures$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMCreateDisasmCPUFeatures$MH = RuntimeHelper.downcallHandle(
        "LLVMCreateDisasmCPUFeatures",
        constants$331.LLVMCreateDisasmCPUFeatures$FUNC
    );
}


