// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$295 {

    static final FunctionDescriptor LLVMParseBitcodeInContext2$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMParseBitcodeInContext2$MH = RuntimeHelper.downcallHandle(
        "LLVMParseBitcodeInContext2",
        constants$295.LLVMParseBitcodeInContext2$FUNC
    );
    static final FunctionDescriptor LLVMGetBitcodeModuleInContext$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetBitcodeModuleInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMGetBitcodeModuleInContext",
        constants$295.LLVMGetBitcodeModuleInContext$FUNC
    );
    static final FunctionDescriptor LLVMGetBitcodeModuleInContext2$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetBitcodeModuleInContext2$MH = RuntimeHelper.downcallHandle(
        "LLVMGetBitcodeModuleInContext2",
        constants$295.LLVMGetBitcodeModuleInContext2$FUNC
    );
    static final FunctionDescriptor LLVMGetBitcodeModule$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetBitcodeModule$MH = RuntimeHelper.downcallHandle(
        "LLVMGetBitcodeModule",
        constants$295.LLVMGetBitcodeModule$FUNC
    );
    static final FunctionDescriptor LLVMGetBitcodeModule2$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetBitcodeModule2$MH = RuntimeHelper.downcallHandle(
        "LLVMGetBitcodeModule2",
        constants$295.LLVMGetBitcodeModule2$FUNC
    );
    static final FunctionDescriptor LLVMWriteBitcodeToFile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMWriteBitcodeToFile$MH = RuntimeHelper.downcallHandle(
        "LLVMWriteBitcodeToFile",
        constants$295.LLVMWriteBitcodeToFile$FUNC
    );
}


