// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$87 {

    static final FunctionDescriptor LLVMSetSourceFileName$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMSetSourceFileName$MH = RuntimeHelper.downcallHandle(
        "LLVMSetSourceFileName",
        constants$87.LLVMSetSourceFileName$FUNC
    );
    static final FunctionDescriptor LLVMGetDataLayoutStr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetDataLayoutStr$MH = RuntimeHelper.downcallHandle(
        "LLVMGetDataLayoutStr",
        constants$87.LLVMGetDataLayoutStr$FUNC
    );
    static final FunctionDescriptor LLVMGetDataLayout$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetDataLayout$MH = RuntimeHelper.downcallHandle(
        "LLVMGetDataLayout",
        constants$87.LLVMGetDataLayout$FUNC
    );
    static final FunctionDescriptor LLVMSetDataLayout$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMSetDataLayout$MH = RuntimeHelper.downcallHandle(
        "LLVMSetDataLayout",
        constants$87.LLVMSetDataLayout$FUNC
    );
    static final FunctionDescriptor LLVMGetTarget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetTarget$MH = RuntimeHelper.downcallHandle(
        "LLVMGetTarget",
        constants$87.LLVMGetTarget$FUNC
    );
    static final FunctionDescriptor LLVMSetTarget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMSetTarget$MH = RuntimeHelper.downcallHandle(
        "LLVMSetTarget",
        constants$87.LLVMSetTarget$FUNC
    );
}


