// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$213 {

    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityAddDependenciesForAll$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityAddDependenciesForAll$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityAddDependenciesForAll",
        constants$213.LLVMOrcMaterializationResponsibilityAddDependenciesForAll$FUNC
    );
    static final FunctionDescriptor LLVMOrcExecutionSessionCreateBareJITDylib$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcExecutionSessionCreateBareJITDylib$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcExecutionSessionCreateBareJITDylib",
        constants$213.LLVMOrcExecutionSessionCreateBareJITDylib$FUNC
    );
    static final FunctionDescriptor LLVMOrcExecutionSessionCreateJITDylib$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcExecutionSessionCreateJITDylib$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcExecutionSessionCreateJITDylib",
        constants$213.LLVMOrcExecutionSessionCreateJITDylib$FUNC
    );
    static final FunctionDescriptor LLVMOrcExecutionSessionGetJITDylibByName$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcExecutionSessionGetJITDylibByName$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcExecutionSessionGetJITDylibByName",
        constants$213.LLVMOrcExecutionSessionGetJITDylibByName$FUNC
    );
    static final FunctionDescriptor LLVMOrcJITDylibCreateResourceTracker$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcJITDylibCreateResourceTracker$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcJITDylibCreateResourceTracker",
        constants$213.LLVMOrcJITDylibCreateResourceTracker$FUNC
    );
    static final FunctionDescriptor LLVMOrcJITDylibGetDefaultResourceTracker$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcJITDylibGetDefaultResourceTracker$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcJITDylibGetDefaultResourceTracker",
        constants$213.LLVMOrcJITDylibGetDefaultResourceTracker$FUNC
    );
}


