// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$259 {

    static final FunctionDescriptor LLVMGetPointerToGlobal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetPointerToGlobal$MH = RuntimeHelper.downcallHandle(
        "LLVMGetPointerToGlobal",
        constants$259.LLVMGetPointerToGlobal$FUNC
    );
    static final FunctionDescriptor LLVMGetGlobalValueAddress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetGlobalValueAddress$MH = RuntimeHelper.downcallHandle(
        "LLVMGetGlobalValueAddress",
        constants$259.LLVMGetGlobalValueAddress$FUNC
    );
    static final FunctionDescriptor LLVMGetFunctionAddress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetFunctionAddress$MH = RuntimeHelper.downcallHandle(
        "LLVMGetFunctionAddress",
        constants$259.LLVMGetFunctionAddress$FUNC
    );
    static final FunctionDescriptor LLVMExecutionEngineGetErrMsg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMExecutionEngineGetErrMsg$MH = RuntimeHelper.downcallHandle(
        "LLVMExecutionEngineGetErrMsg",
        constants$259.LLVMExecutionEngineGetErrMsg$FUNC
    );
    static final FunctionDescriptor LLVMMemoryManagerAllocateCodeSectionCallback$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMMemoryManagerAllocateCodeSectionCallback$MH = RuntimeHelper.downcallHandle(
        constants$259.LLVMMemoryManagerAllocateCodeSectionCallback$FUNC
    );
}


