// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$322 {

    static final FunctionDescriptor LLVMDIBuilderCreateQualifiedType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateQualifiedType$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateQualifiedType",
        constants$322.LLVMDIBuilderCreateQualifiedType$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateReferenceType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateReferenceType$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateReferenceType",
        constants$322.LLVMDIBuilderCreateReferenceType$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateNullPtrType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateNullPtrType$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateNullPtrType",
        constants$322.LLVMDIBuilderCreateNullPtrType$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateTypedef$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateTypedef$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateTypedef",
        constants$322.LLVMDIBuilderCreateTypedef$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateInheritance$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateInheritance$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateInheritance",
        constants$322.LLVMDIBuilderCreateInheritance$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateForwardDecl$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateForwardDecl$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateForwardDecl",
        constants$322.LLVMDIBuilderCreateForwardDecl$FUNC
    );
}


