// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$110 {

    static final FunctionDescriptor LLVMIsAConstantDataVector$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantDataVector$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantDataVector",
        constants$110.LLVMIsAConstantDataVector$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantExpr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantExpr$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantExpr",
        constants$110.LLVMIsAConstantExpr$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantFP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantFP$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantFP",
        constants$110.LLVMIsAConstantFP$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantInt$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantInt$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantInt",
        constants$110.LLVMIsAConstantInt$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantPointerNull$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantPointerNull$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantPointerNull",
        constants$110.LLVMIsAConstantPointerNull$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantStruct$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantStruct$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantStruct",
        constants$110.LLVMIsAConstantStruct$FUNC
    );
}


