// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$102 {

    static final FunctionDescriptor LLVMIsPackedStruct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsPackedStruct$MH = RuntimeHelper.downcallHandle(
        "LLVMIsPackedStruct",
        constants$102.LLVMIsPackedStruct$FUNC
    );
    static final FunctionDescriptor LLVMIsOpaqueStruct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsOpaqueStruct$MH = RuntimeHelper.downcallHandle(
        "LLVMIsOpaqueStruct",
        constants$102.LLVMIsOpaqueStruct$FUNC
    );
    static final FunctionDescriptor LLVMIsLiteralStruct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsLiteralStruct$MH = RuntimeHelper.downcallHandle(
        "LLVMIsLiteralStruct",
        constants$102.LLVMIsLiteralStruct$FUNC
    );
    static final FunctionDescriptor LLVMGetElementType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetElementType$MH = RuntimeHelper.downcallHandle(
        "LLVMGetElementType",
        constants$102.LLVMGetElementType$FUNC
    );
    static final FunctionDescriptor LLVMGetSubtypes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetSubtypes$MH = RuntimeHelper.downcallHandle(
        "LLVMGetSubtypes",
        constants$102.LLVMGetSubtypes$FUNC
    );
    static final FunctionDescriptor LLVMGetNumContainedTypes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetNumContainedTypes$MH = RuntimeHelper.downcallHandle(
        "LLVMGetNumContainedTypes",
        constants$102.LLVMGetNumContainedTypes$FUNC
    );
}


