// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$163 {

    static final FunctionDescriptor LLVMGetInstructionCallConv$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetInstructionCallConv$MH = RuntimeHelper.downcallHandle(
        "LLVMGetInstructionCallConv",
        constants$163.LLVMGetInstructionCallConv$FUNC
    );
    static final FunctionDescriptor LLVMSetInstrParamAlignment$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMSetInstrParamAlignment$MH = RuntimeHelper.downcallHandle(
        "LLVMSetInstrParamAlignment",
        constants$163.LLVMSetInstrParamAlignment$FUNC
    );
    static final FunctionDescriptor LLVMAddCallSiteAttribute$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddCallSiteAttribute$MH = RuntimeHelper.downcallHandle(
        "LLVMAddCallSiteAttribute",
        constants$163.LLVMAddCallSiteAttribute$FUNC
    );
    static final FunctionDescriptor LLVMGetCallSiteAttributeCount$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMGetCallSiteAttributeCount$MH = RuntimeHelper.downcallHandle(
        "LLVMGetCallSiteAttributeCount",
        constants$163.LLVMGetCallSiteAttributeCount$FUNC
    );
    static final FunctionDescriptor LLVMGetCallSiteAttributes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetCallSiteAttributes$MH = RuntimeHelper.downcallHandle(
        "LLVMGetCallSiteAttributes",
        constants$163.LLVMGetCallSiteAttributes$FUNC
    );
    static final FunctionDescriptor LLVMGetCallSiteEnumAttribute$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMGetCallSiteEnumAttribute$MH = RuntimeHelper.downcallHandle(
        "LLVMGetCallSiteEnumAttribute",
        constants$163.LLVMGetCallSiteEnumAttribute$FUNC
    );
}


