// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$109 {

    static final FunctionDescriptor LLVMIsAConstant$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstant$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstant",
        constants$109.LLVMIsAConstant$FUNC
    );
    static final FunctionDescriptor LLVMIsABlockAddress$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsABlockAddress$MH = RuntimeHelper.downcallHandle(
        "LLVMIsABlockAddress",
        constants$109.LLVMIsABlockAddress$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantAggregateZero$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantAggregateZero$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantAggregateZero",
        constants$109.LLVMIsAConstantAggregateZero$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantArray$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantArray$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantArray",
        constants$109.LLVMIsAConstantArray$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantDataSequential$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantDataSequential$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantDataSequential",
        constants$109.LLVMIsAConstantDataSequential$FUNC
    );
    static final FunctionDescriptor LLVMIsAConstantDataArray$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAConstantDataArray$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAConstantDataArray",
        constants$109.LLVMIsAConstantDataArray$FUNC
    );
}


