// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$274 {

    static final FunctionDescriptor lto_module_create_in_codegen_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_create_in_codegen_context$MH = RuntimeHelper.downcallHandle(
        "lto_module_create_in_codegen_context",
        constants$274.lto_module_create_in_codegen_context$FUNC
    );
    static final FunctionDescriptor lto_module_create_from_fd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle lto_module_create_from_fd$MH = RuntimeHelper.downcallHandle(
        "lto_module_create_from_fd",
        constants$274.lto_module_create_from_fd$FUNC
    );
    static final FunctionDescriptor lto_module_create_from_fd_at_offset$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle lto_module_create_from_fd_at_offset$MH = RuntimeHelper.downcallHandle(
        "lto_module_create_from_fd_at_offset",
        constants$274.lto_module_create_from_fd_at_offset$FUNC
    );
    static final FunctionDescriptor lto_module_dispose$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_dispose$MH = RuntimeHelper.downcallHandle(
        "lto_module_dispose",
        constants$274.lto_module_dispose$FUNC
    );
    static final FunctionDescriptor lto_module_get_target_triple$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_get_target_triple$MH = RuntimeHelper.downcallHandle(
        "lto_module_get_target_triple",
        constants$274.lto_module_get_target_triple$FUNC
    );
    static final FunctionDescriptor lto_module_set_target_triple$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_set_target_triple$MH = RuntimeHelper.downcallHandle(
        "lto_module_set_target_triple",
        constants$274.lto_module_set_target_triple$FUNC
    );
}


