// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$133 {

    static final FunctionDescriptor LLVMConstICmp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstICmp$MH = RuntimeHelper.downcallHandle(
        "LLVMConstICmp",
        constants$133.LLVMConstICmp$FUNC
    );
    static final FunctionDescriptor LLVMConstFCmp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstFCmp$MH = RuntimeHelper.downcallHandle(
        "LLVMConstFCmp",
        constants$133.LLVMConstFCmp$FUNC
    );
    static final FunctionDescriptor LLVMConstShl$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstShl$MH = RuntimeHelper.downcallHandle(
        "LLVMConstShl",
        constants$133.LLVMConstShl$FUNC
    );
    static final FunctionDescriptor LLVMConstLShr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstLShr$MH = RuntimeHelper.downcallHandle(
        "LLVMConstLShr",
        constants$133.LLVMConstLShr$FUNC
    );
    static final FunctionDescriptor LLVMConstAShr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstAShr$MH = RuntimeHelper.downcallHandle(
        "LLVMConstAShr",
        constants$133.LLVMConstAShr$FUNC
    );
    static final FunctionDescriptor LLVMConstGEP2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMConstGEP2$MH = RuntimeHelper.downcallHandle(
        "LLVMConstGEP2",
        constants$133.LLVMConstGEP2$FUNC
    );
}


