// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$132 {

    static final FunctionDescriptor LLVMConstMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstMul$MH = RuntimeHelper.downcallHandle(
        "LLVMConstMul",
        constants$132.LLVMConstMul$FUNC
    );
    static final FunctionDescriptor LLVMConstNSWMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstNSWMul$MH = RuntimeHelper.downcallHandle(
        "LLVMConstNSWMul",
        constants$132.LLVMConstNSWMul$FUNC
    );
    static final FunctionDescriptor LLVMConstNUWMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstNUWMul$MH = RuntimeHelper.downcallHandle(
        "LLVMConstNUWMul",
        constants$132.LLVMConstNUWMul$FUNC
    );
    static final FunctionDescriptor LLVMConstAnd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstAnd$MH = RuntimeHelper.downcallHandle(
        "LLVMConstAnd",
        constants$132.LLVMConstAnd$FUNC
    );
    static final FunctionDescriptor LLVMConstOr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstOr$MH = RuntimeHelper.downcallHandle(
        "LLVMConstOr",
        constants$132.LLVMConstOr$FUNC
    );
    static final FunctionDescriptor LLVMConstXor$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstXor$MH = RuntimeHelper.downcallHandle(
        "LLVMConstXor",
        constants$132.LLVMConstXor$FUNC
    );
}


