// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$264 {

    static final FunctionDescriptor mlirCreateGPUGpuAsyncRegionPass$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirPass"));
    static final MethodHandle mlirCreateGPUGpuAsyncRegionPass$MH = RuntimeHelper.downcallHandle(
        "mlirCreateGPUGpuAsyncRegionPass",
        constants$264.mlirCreateGPUGpuAsyncRegionPass$FUNC
    );
    static final FunctionDescriptor mlirRegisterGPUGpuAsyncRegionPass$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle mlirRegisterGPUGpuAsyncRegionPass$MH = RuntimeHelper.downcallHandle(
        "mlirRegisterGPUGpuAsyncRegionPass",
        constants$264.mlirRegisterGPUGpuAsyncRegionPass$FUNC
    );
    static final FunctionDescriptor mlirCreateGPUGpuKernelOutlining$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirPass"));
    static final MethodHandle mlirCreateGPUGpuKernelOutlining$MH = RuntimeHelper.downcallHandle(
        "mlirCreateGPUGpuKernelOutlining",
        constants$264.mlirCreateGPUGpuKernelOutlining$FUNC
    );
    static final FunctionDescriptor mlirRegisterGPUGpuKernelOutlining$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle mlirRegisterGPUGpuKernelOutlining$MH = RuntimeHelper.downcallHandle(
        "mlirRegisterGPUGpuKernelOutlining",
        constants$264.mlirRegisterGPUGpuKernelOutlining$FUNC
    );
    static final FunctionDescriptor mlirCreateGPUGpuLaunchSinkIndexComputations$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirPass"));
    static final MethodHandle mlirCreateGPUGpuLaunchSinkIndexComputations$MH = RuntimeHelper.downcallHandle(
        "mlirCreateGPUGpuLaunchSinkIndexComputations",
        constants$264.mlirCreateGPUGpuLaunchSinkIndexComputations$FUNC
    );
    static final FunctionDescriptor mlirRegisterGPUGpuLaunchSinkIndexComputations$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle mlirRegisterGPUGpuLaunchSinkIndexComputations$MH = RuntimeHelper.downcallHandle(
        "mlirRegisterGPUGpuLaunchSinkIndexComputations",
        constants$264.mlirRegisterGPUGpuLaunchSinkIndexComputations$FUNC
    );
}


