// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$329 {

    static final FunctionDescriptor LLVMGetMetadataKind$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetMetadataKind$MH = RuntimeHelper.downcallHandle(
        "LLVMGetMetadataKind",
        constants$329.LLVMGetMetadataKind$FUNC
    );
    static final FunctionDescriptor mlirGetDialectHandle__scf__$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirDialectHandle"));
    static final MethodHandle mlirGetDialectHandle__scf__$MH = RuntimeHelper.downcallHandle(
        "mlirGetDialectHandle__scf__",
        constants$329.mlirGetDialectHandle__scf__$FUNC
    );
    static final FunctionDescriptor mlirGetDialectHandle__tensor__$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirDialectHandle"));
    static final MethodHandle mlirGetDialectHandle__tensor__$MH = RuntimeHelper.downcallHandle(
        "mlirGetDialectHandle__tensor__",
        constants$329.mlirGetDialectHandle__tensor__$FUNC
    );
    static final FunctionDescriptor mlirGetDialectHandle__llvm__$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirDialectHandle"));
    static final MethodHandle mlirGetDialectHandle__llvm__$MH = RuntimeHelper.downcallHandle(
        "mlirGetDialectHandle__llvm__",
        constants$329.mlirGetDialectHandle__llvm__$FUNC
    );
    static final FunctionDescriptor mlirLLVMPointerTypeGet$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirType"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mlirLLVMPointerTypeGet$MH = RuntimeHelper.downcallHandle(
        "mlirLLVMPointerTypeGet",
        constants$329.mlirLLVMPointerTypeGet$FUNC
    );
    static final FunctionDescriptor mlirLLVMVoidTypeGet$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirType"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirContext")
    );
    static final MethodHandle mlirLLVMVoidTypeGet$MH = RuntimeHelper.downcallHandle(
        "mlirLLVMVoidTypeGet",
        constants$329.mlirLLVMVoidTypeGet$FUNC
    );
}


