// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$165 {

    static final FunctionDescriptor LLVMSetTailCall$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMSetTailCall$MH = RuntimeHelper.downcallHandle(
        "LLVMSetTailCall",
        constants$165.LLVMSetTailCall$FUNC
    );
    static final FunctionDescriptor LLVMGetNormalDest$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetNormalDest$MH = RuntimeHelper.downcallHandle(
        "LLVMGetNormalDest",
        constants$165.LLVMGetNormalDest$FUNC
    );
    static final FunctionDescriptor LLVMGetUnwindDest$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetUnwindDest$MH = RuntimeHelper.downcallHandle(
        "LLVMGetUnwindDest",
        constants$165.LLVMGetUnwindDest$FUNC
    );
    static final FunctionDescriptor LLVMSetNormalDest$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMSetNormalDest$MH = RuntimeHelper.downcallHandle(
        "LLVMSetNormalDest",
        constants$165.LLVMSetNormalDest$FUNC
    );
    static final FunctionDescriptor LLVMSetUnwindDest$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMSetUnwindDest$MH = RuntimeHelper.downcallHandle(
        "LLVMSetUnwindDest",
        constants$165.LLVMSetUnwindDest$FUNC
    );
    static final FunctionDescriptor LLVMGetNumSuccessors$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetNumSuccessors$MH = RuntimeHelper.downcallHandle(
        "LLVMGetNumSuccessors",
        constants$165.LLVMGetNumSuccessors$FUNC
    );
}


