// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$129 {

    static final FunctionDescriptor LLVMConstArray2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMConstArray2$MH = RuntimeHelper.downcallHandle(
        "LLVMConstArray2",
        constants$129.LLVMConstArray2$FUNC
    );
    static final FunctionDescriptor LLVMConstNamedStruct$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMConstNamedStruct$MH = RuntimeHelper.downcallHandle(
        "LLVMConstNamedStruct",
        constants$129.LLVMConstNamedStruct$FUNC
    );
    static final FunctionDescriptor LLVMGetAggregateElement$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMGetAggregateElement$MH = RuntimeHelper.downcallHandle(
        "LLVMGetAggregateElement",
        constants$129.LLVMGetAggregateElement$FUNC
    );
    static final FunctionDescriptor LLVMGetElementAsConstant$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMGetElementAsConstant$MH = RuntimeHelper.downcallHandle(
        "LLVMGetElementAsConstant",
        constants$129.LLVMGetElementAsConstant$FUNC
    );
    static final FunctionDescriptor LLVMConstVector$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMConstVector$MH = RuntimeHelper.downcallHandle(
        "LLVMConstVector",
        constants$129.LLVMConstVector$FUNC
    );
    static final FunctionDescriptor LLVMGetConstOpcode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetConstOpcode$MH = RuntimeHelper.downcallHandle(
        "LLVMGetConstOpcode",
        constants$129.LLVMGetConstOpcode$FUNC
    );
}


