// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$147 {

    static final FunctionDescriptor LLVMGetPersonalityFn$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetPersonalityFn$MH = RuntimeHelper.downcallHandle(
        "LLVMGetPersonalityFn",
        constants$147.LLVMGetPersonalityFn$FUNC
    );
    static final FunctionDescriptor LLVMSetPersonalityFn$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMSetPersonalityFn$MH = RuntimeHelper.downcallHandle(
        "LLVMSetPersonalityFn",
        constants$147.LLVMSetPersonalityFn$FUNC
    );
    static final FunctionDescriptor LLVMLookupIntrinsicID$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMLookupIntrinsicID$MH = RuntimeHelper.downcallHandle(
        "LLVMLookupIntrinsicID",
        constants$147.LLVMLookupIntrinsicID$FUNC
    );
    static final FunctionDescriptor LLVMGetIntrinsicID$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetIntrinsicID$MH = RuntimeHelper.downcallHandle(
        "LLVMGetIntrinsicID",
        constants$147.LLVMGetIntrinsicID$FUNC
    );
    static final FunctionDescriptor LLVMGetIntrinsicDeclaration$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMGetIntrinsicDeclaration$MH = RuntimeHelper.downcallHandle(
        "LLVMGetIntrinsicDeclaration",
        constants$147.LLVMGetIntrinsicDeclaration$FUNC
    );
    static final FunctionDescriptor LLVMIntrinsicGetType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMIntrinsicGetType$MH = RuntimeHelper.downcallHandle(
        "LLVMIntrinsicGetType",
        constants$147.LLVMIntrinsicGetType$FUNC
    );
}


