// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$319 {

    static final FunctionDescriptor LLVMDIBuilderCreateSubroutineType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateSubroutineType$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateSubroutineType",
        constants$319.LLVMDIBuilderCreateSubroutineType$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateMacro$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateMacro$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateMacro",
        constants$319.LLVMDIBuilderCreateMacro$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateTempMacroFile$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateTempMacroFile$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateTempMacroFile",
        constants$319.LLVMDIBuilderCreateTempMacroFile$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateEnumerator$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateEnumerator$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateEnumerator",
        constants$319.LLVMDIBuilderCreateEnumerator$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateEnumerationType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateEnumerationType$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateEnumerationType",
        constants$319.LLVMDIBuilderCreateEnumerationType$FUNC
    );
    static final FunctionDescriptor LLVMDIBuilderCreateUnionType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMDIBuilderCreateUnionType$MH = RuntimeHelper.downcallHandle(
        "LLVMDIBuilderCreateUnionType",
        constants$319.LLVMDIBuilderCreateUnionType$FUNC
    );
}


