// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$174 {

    static final FunctionDescriptor LLVMBuildCleanupPad$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildCleanupPad$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildCleanupPad",
        constants$174.LLVMBuildCleanupPad$FUNC
    );
    static final FunctionDescriptor LLVMBuildCatchSwitch$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildCatchSwitch$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildCatchSwitch",
        constants$174.LLVMBuildCatchSwitch$FUNC
    );
    static final FunctionDescriptor LLVMAddCase$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddCase$MH = RuntimeHelper.downcallHandle(
        "LLVMAddCase",
        constants$174.LLVMAddCase$FUNC
    );
    static final FunctionDescriptor LLVMAddDestination$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddDestination$MH = RuntimeHelper.downcallHandle(
        "LLVMAddDestination",
        constants$174.LLVMAddDestination$FUNC
    );
    static final FunctionDescriptor LLVMGetNumClauses$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetNumClauses$MH = RuntimeHelper.downcallHandle(
        "LLVMGetNumClauses",
        constants$174.LLVMGetNumClauses$FUNC
    );
    static final FunctionDescriptor LLVMGetClause$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMGetClause$MH = RuntimeHelper.downcallHandle(
        "LLVMGetClause",
        constants$174.LLVMGetClause$FUNC
    );
}


