// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$171 {

    static final FunctionDescriptor LLVMBuilderGetDefaultFPMathTag$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuilderGetDefaultFPMathTag$MH = RuntimeHelper.downcallHandle(
        "LLVMBuilderGetDefaultFPMathTag",
        constants$171.LLVMBuilderGetDefaultFPMathTag$FUNC
    );
    static final FunctionDescriptor LLVMBuilderSetDefaultFPMathTag$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuilderSetDefaultFPMathTag$MH = RuntimeHelper.downcallHandle(
        "LLVMBuilderSetDefaultFPMathTag",
        constants$171.LLVMBuilderSetDefaultFPMathTag$FUNC
    );
    static final FunctionDescriptor LLVMSetCurrentDebugLocation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMSetCurrentDebugLocation$MH = RuntimeHelper.downcallHandle(
        "LLVMSetCurrentDebugLocation",
        constants$171.LLVMSetCurrentDebugLocation$FUNC
    );
    static final FunctionDescriptor LLVMGetCurrentDebugLocation$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetCurrentDebugLocation$MH = RuntimeHelper.downcallHandle(
        "LLVMGetCurrentDebugLocation",
        constants$171.LLVMGetCurrentDebugLocation$FUNC
    );
    static final FunctionDescriptor LLVMBuildRetVoid$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildRetVoid$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildRetVoid",
        constants$171.LLVMBuildRetVoid$FUNC
    );
    static final FunctionDescriptor LLVMBuildRet$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildRet$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildRet",
        constants$171.LLVMBuildRet$FUNC
    );
}


