// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$188 {

    static final FunctionDescriptor LLVMBuildZExtOrBitCast$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildZExtOrBitCast$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildZExtOrBitCast",
        constants$188.LLVMBuildZExtOrBitCast$FUNC
    );
    static final FunctionDescriptor LLVMBuildSExtOrBitCast$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildSExtOrBitCast$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildSExtOrBitCast",
        constants$188.LLVMBuildSExtOrBitCast$FUNC
    );
    static final FunctionDescriptor LLVMBuildTruncOrBitCast$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildTruncOrBitCast$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildTruncOrBitCast",
        constants$188.LLVMBuildTruncOrBitCast$FUNC
    );
    static final FunctionDescriptor LLVMBuildCast$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildCast$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildCast",
        constants$188.LLVMBuildCast$FUNC
    );
    static final FunctionDescriptor LLVMBuildPointerCast$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildPointerCast$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildPointerCast",
        constants$188.LLVMBuildPointerCast$FUNC
    );
    static final FunctionDescriptor LLVMBuildIntCast2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildIntCast2$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildIntCast2",
        constants$188.LLVMBuildIntCast2$FUNC
    );
}


