// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$141 {

    static final FunctionDescriptor LLVMSetAlignment$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMSetAlignment$MH = RuntimeHelper.downcallHandle(
        "LLVMSetAlignment",
        constants$141.LLVMSetAlignment$FUNC
    );
    static final FunctionDescriptor LLVMGlobalSetMetadata$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGlobalSetMetadata$MH = RuntimeHelper.downcallHandle(
        "LLVMGlobalSetMetadata",
        constants$141.LLVMGlobalSetMetadata$FUNC
    );
    static final FunctionDescriptor LLVMGlobalEraseMetadata$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMGlobalEraseMetadata$MH = RuntimeHelper.downcallHandle(
        "LLVMGlobalEraseMetadata",
        constants$141.LLVMGlobalEraseMetadata$FUNC
    );
    static final FunctionDescriptor LLVMGlobalClearMetadata$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGlobalClearMetadata$MH = RuntimeHelper.downcallHandle(
        "LLVMGlobalClearMetadata",
        constants$141.LLVMGlobalClearMetadata$FUNC
    );
    static final FunctionDescriptor LLVMGlobalCopyAllMetadata$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGlobalCopyAllMetadata$MH = RuntimeHelper.downcallHandle(
        "LLVMGlobalCopyAllMetadata",
        constants$141.LLVMGlobalCopyAllMetadata$FUNC
    );
    static final FunctionDescriptor LLVMDisposeValueMetadataEntries$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMDisposeValueMetadataEntries$MH = RuntimeHelper.downcallHandle(
        "LLVMDisposeValueMetadataEntries",
        constants$141.LLVMDisposeValueMetadataEntries$FUNC
    );
}


