// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$288 {

    static final FunctionDescriptor LLVMPassBuilderOptionsSetLoopUnrolling$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMPassBuilderOptionsSetLoopUnrolling$MH = RuntimeHelper.downcallHandle(
        "LLVMPassBuilderOptionsSetLoopUnrolling",
        constants$288.LLVMPassBuilderOptionsSetLoopUnrolling$FUNC
    );
    static final FunctionDescriptor LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll$MH = RuntimeHelper.downcallHandle(
        "LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll",
        constants$288.LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll$FUNC
    );
    static final FunctionDescriptor LLVMPassBuilderOptionsSetLicmMssaOptCap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMPassBuilderOptionsSetLicmMssaOptCap$MH = RuntimeHelper.downcallHandle(
        "LLVMPassBuilderOptionsSetLicmMssaOptCap",
        constants$288.LLVMPassBuilderOptionsSetLicmMssaOptCap$FUNC
    );
    static final FunctionDescriptor LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap$MH = RuntimeHelper.downcallHandle(
        "LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap",
        constants$288.LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap$FUNC
    );
    static final FunctionDescriptor LLVMPassBuilderOptionsSetCallGraphProfile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMPassBuilderOptionsSetCallGraphProfile$MH = RuntimeHelper.downcallHandle(
        "LLVMPassBuilderOptionsSetCallGraphProfile",
        constants$288.LLVMPassBuilderOptionsSetCallGraphProfile$FUNC
    );
    static final FunctionDescriptor LLVMPassBuilderOptionsSetMergeFunctions$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMPassBuilderOptionsSetMergeFunctions$MH = RuntimeHelper.downcallHandle(
        "LLVMPassBuilderOptionsSetMergeFunctions",
        constants$288.LLVMPassBuilderOptionsSetMergeFunctions$FUNC
    );
}


