// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$172 {

    static final FunctionDescriptor LLVMBuildAggregateRet$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMBuildAggregateRet$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildAggregateRet",
        constants$172.LLVMBuildAggregateRet$FUNC
    );
    static final FunctionDescriptor LLVMBuildBr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildBr$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildBr",
        constants$172.LLVMBuildBr$FUNC
    );
    static final FunctionDescriptor LLVMBuildCondBr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildCondBr$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildCondBr",
        constants$172.LLVMBuildCondBr$FUNC
    );
    static final FunctionDescriptor LLVMBuildSwitch$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMBuildSwitch$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildSwitch",
        constants$172.LLVMBuildSwitch$FUNC
    );
    static final FunctionDescriptor LLVMBuildIndirectBr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMBuildIndirectBr$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildIndirectBr",
        constants$172.LLVMBuildIndirectBr$FUNC
    );
    static final FunctionDescriptor LLVMBuildInvoke2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildInvoke2$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildInvoke2",
        constants$172.LLVMBuildInvoke2$FUNC
    );
}


