// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$217 {

    static final FunctionDescriptor LLVMOrcJITTargetMachineBuilderSetTargetTriple$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcJITTargetMachineBuilderSetTargetTriple$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcJITTargetMachineBuilderSetTargetTriple",
        constants$217.LLVMOrcJITTargetMachineBuilderSetTargetTriple$FUNC
    );
    static final FunctionDescriptor LLVMOrcObjectLayerAddObjectFile$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcObjectLayerAddObjectFile$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcObjectLayerAddObjectFile",
        constants$217.LLVMOrcObjectLayerAddObjectFile$FUNC
    );
    static final FunctionDescriptor LLVMOrcObjectLayerAddObjectFileWithRT$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcObjectLayerAddObjectFileWithRT$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcObjectLayerAddObjectFileWithRT",
        constants$217.LLVMOrcObjectLayerAddObjectFileWithRT$FUNC
    );
    static final FunctionDescriptor LLVMOrcObjectLayerEmit$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcObjectLayerEmit$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcObjectLayerEmit",
        constants$217.LLVMOrcObjectLayerEmit$FUNC
    );
    static final FunctionDescriptor LLVMOrcDisposeObjectLayer$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcDisposeObjectLayer$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcDisposeObjectLayer",
        constants$217.LLVMOrcDisposeObjectLayer$FUNC
    );
    static final FunctionDescriptor LLVMOrcIRTransformLayerEmit$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcIRTransformLayerEmit$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcIRTransformLayerEmit",
        constants$217.LLVMOrcIRTransformLayerEmit$FUNC
    );
}


