// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$100 {

    static final FunctionDescriptor LLVMIsFunctionVarArg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsFunctionVarArg$MH = RuntimeHelper.downcallHandle(
        "LLVMIsFunctionVarArg",
        constants$100.LLVMIsFunctionVarArg$FUNC
    );
    static final FunctionDescriptor LLVMGetReturnType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetReturnType$MH = RuntimeHelper.downcallHandle(
        "LLVMGetReturnType",
        constants$100.LLVMGetReturnType$FUNC
    );
    static final FunctionDescriptor LLVMCountParamTypes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMCountParamTypes$MH = RuntimeHelper.downcallHandle(
        "LLVMCountParamTypes",
        constants$100.LLVMCountParamTypes$FUNC
    );
    static final FunctionDescriptor LLVMGetParamTypes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetParamTypes$MH = RuntimeHelper.downcallHandle(
        "LLVMGetParamTypes",
        constants$100.LLVMGetParamTypes$FUNC
    );
    static final FunctionDescriptor LLVMStructTypeInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMStructTypeInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMStructTypeInContext",
        constants$100.LLVMStructTypeInContext$FUNC
    );
    static final FunctionDescriptor LLVMStructType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMStructType$MH = RuntimeHelper.downcallHandle(
        "LLVMStructType",
        constants$100.LLVMStructType$FUNC
    );
}


