// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$5 {

    static final FunctionDescriptor mlirDialectIsNull$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialect")
    );
    static final MethodHandle mlirDialectIsNull$MH = RuntimeHelper.downcallHandle(
        "mlirDialectIsNull",
        constants$5.mlirDialectIsNull$FUNC
    );
    static final FunctionDescriptor mlirDialectEqual$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialect"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialect")
    );
    static final MethodHandle mlirDialectEqual$MH = RuntimeHelper.downcallHandle(
        "mlirDialectEqual",
        constants$5.mlirDialectEqual$FUNC
    );
    static final FunctionDescriptor mlirDialectGetNamespace$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("length")
    ).withName("MlirStringRef"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialect")
    );
    static final MethodHandle mlirDialectGetNamespace$MH = RuntimeHelper.downcallHandle(
        "mlirDialectGetNamespace",
        constants$5.mlirDialectGetNamespace$FUNC
    );
    static final FunctionDescriptor mlirDialectHandleGetNamespace$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("length")
    ).withName("MlirStringRef"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialectHandle")
    );
    static final MethodHandle mlirDialectHandleGetNamespace$MH = RuntimeHelper.downcallHandle(
        "mlirDialectHandleGetNamespace",
        constants$5.mlirDialectHandleGetNamespace$FUNC
    );
    static final FunctionDescriptor mlirDialectHandleInsertDialect$FUNC = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialectHandle"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialectRegistry")
    );
    static final MethodHandle mlirDialectHandleInsertDialect$MH = RuntimeHelper.downcallHandle(
        "mlirDialectHandleInsertDialect",
        constants$5.mlirDialectHandleInsertDialect$FUNC
    );
    static final FunctionDescriptor mlirDialectHandleRegisterDialect$FUNC = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirDialectHandle"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirContext")
    );
    static final MethodHandle mlirDialectHandleRegisterDialect$MH = RuntimeHelper.downcallHandle(
        "mlirDialectHandleRegisterDialect",
        constants$5.mlirDialectHandleRegisterDialect$FUNC
    );
}


