// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$204 {

    static final FunctionDescriptor LLVMAddAnalysisPasses$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAddAnalysisPasses$MH = RuntimeHelper.downcallHandle(
        "LLVMAddAnalysisPasses",
        constants$204.LLVMAddAnalysisPasses$FUNC
    );
    static final FunctionDescriptor LLVMOrcErrorReporterFunction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcErrorReporterFunction$MH = RuntimeHelper.downcallHandle(
        constants$204.LLVMOrcErrorReporterFunction$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationUnitMaterializeFunction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationUnitMaterializeFunction$MH = RuntimeHelper.downcallHandle(
        constants$204.LLVMOrcMaterializationUnitMaterializeFunction$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationUnitDiscardFunction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


