// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$211 {

    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityGetSymbols$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityGetSymbols$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityGetSymbols",
        constants$211.LLVMOrcMaterializationResponsibilityGetSymbols$FUNC
    );
    static final FunctionDescriptor LLVMOrcDisposeCSymbolFlagsMap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcDisposeCSymbolFlagsMap$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcDisposeCSymbolFlagsMap",
        constants$211.LLVMOrcDisposeCSymbolFlagsMap$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityGetInitializerSymbol$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityGetInitializerSymbol$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityGetInitializerSymbol",
        constants$211.LLVMOrcMaterializationResponsibilityGetInitializerSymbol$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityGetRequestedSymbols$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityGetRequestedSymbols$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityGetRequestedSymbols",
        constants$211.LLVMOrcMaterializationResponsibilityGetRequestedSymbols$FUNC
    );
    static final FunctionDescriptor LLVMOrcDisposeSymbols$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcDisposeSymbols$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcDisposeSymbols",
        constants$211.LLVMOrcDisposeSymbols$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityNotifyResolved$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityNotifyResolved$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityNotifyResolved",
        constants$211.LLVMOrcMaterializationResponsibilityNotifyResolved$FUNC
    );
}


