// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$97 {

    static final FunctionDescriptor LLVMInt128Type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle LLVMInt128Type$MH = RuntimeHelper.downcallHandle(
        "LLVMInt128Type",
        constants$97.LLVMInt128Type$FUNC
    );
    static final FunctionDescriptor LLVMIntType$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMIntType$MH = RuntimeHelper.downcallHandle(
        "LLVMIntType",
        constants$97.LLVMIntType$FUNC
    );
    static final FunctionDescriptor LLVMGetIntTypeWidth$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetIntTypeWidth$MH = RuntimeHelper.downcallHandle(
        "LLVMGetIntTypeWidth",
        constants$97.LLVMGetIntTypeWidth$FUNC
    );
    static final FunctionDescriptor LLVMHalfTypeInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMHalfTypeInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMHalfTypeInContext",
        constants$97.LLVMHalfTypeInContext$FUNC
    );
    static final FunctionDescriptor LLVMBFloatTypeInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBFloatTypeInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMBFloatTypeInContext",
        constants$97.LLVMBFloatTypeInContext$FUNC
    );
    static final FunctionDescriptor LLVMFloatTypeInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMFloatTypeInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMFloatTypeInContext",
        constants$97.LLVMFloatTypeInContext$FUNC
    );
}


