// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$178 {

    static final FunctionDescriptor LLVMBuildMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildMul$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildMul",
        constants$178.LLVMBuildMul$FUNC
    );
    static final FunctionDescriptor LLVMBuildNSWMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildNSWMul$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildNSWMul",
        constants$178.LLVMBuildNSWMul$FUNC
    );
    static final FunctionDescriptor LLVMBuildNUWMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildNUWMul$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildNUWMul",
        constants$178.LLVMBuildNUWMul$FUNC
    );
    static final FunctionDescriptor LLVMBuildFMul$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildFMul$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildFMul",
        constants$178.LLVMBuildFMul$FUNC
    );
    static final FunctionDescriptor LLVMBuildUDiv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildUDiv$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildUDiv",
        constants$178.LLVMBuildUDiv$FUNC
    );
    static final FunctionDescriptor LLVMBuildExactUDiv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildExactUDiv$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildExactUDiv",
        constants$178.LLVMBuildExactUDiv$FUNC
    );
}


