// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$278 {

    static final FunctionDescriptor lto_codegen_set_assembler_args$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle lto_codegen_set_assembler_args$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_set_assembler_args",
        constants$278.lto_codegen_set_assembler_args$FUNC
    );
    static final FunctionDescriptor lto_codegen_add_must_preserve_symbol$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_add_must_preserve_symbol$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_add_must_preserve_symbol",
        constants$278.lto_codegen_add_must_preserve_symbol$FUNC
    );
    static final FunctionDescriptor lto_codegen_write_merged_modules$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_write_merged_modules$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_write_merged_modules",
        constants$278.lto_codegen_write_merged_modules$FUNC
    );
    static final FunctionDescriptor lto_codegen_compile$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_compile$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_compile",
        constants$278.lto_codegen_compile$FUNC
    );
    static final FunctionDescriptor lto_codegen_compile_to_file$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_compile_to_file$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_compile_to_file",
        constants$278.lto_codegen_compile_to_file$FUNC
    );
    static final FunctionDescriptor lto_codegen_optimize$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_optimize$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_optimize",
        constants$278.lto_codegen_optimize$FUNC
    );
}


