// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$282 {

    static final FunctionDescriptor thinlto_module_get_object$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("Buffer"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("Size")
    ),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle thinlto_module_get_object$MH = RuntimeHelper.downcallHandle(
        "thinlto_module_get_object",
        constants$282.thinlto_module_get_object$FUNC
    );
    static final FunctionDescriptor thinlto_module_get_num_object_files$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle thinlto_module_get_num_object_files$MH = RuntimeHelper.downcallHandle(
        "thinlto_module_get_num_object_files",
        constants$282.thinlto_module_get_num_object_files$FUNC
    );
    static final FunctionDescriptor thinlto_module_get_object_file$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle thinlto_module_get_object_file$MH = RuntimeHelper.downcallHandle(
        "thinlto_module_get_object_file",
        constants$282.thinlto_module_get_object_file$FUNC
    );
    static final FunctionDescriptor thinlto_codegen_set_pic_model$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle thinlto_codegen_set_pic_model$MH = RuntimeHelper.downcallHandle(
        "thinlto_codegen_set_pic_model",
        constants$282.thinlto_codegen_set_pic_model$FUNC
    );
    static final FunctionDescriptor thinlto_codegen_set_savetemps_dir$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle thinlto_codegen_set_savetemps_dir$MH = RuntimeHelper.downcallHandle(
        "thinlto_codegen_set_savetemps_dir",
        constants$282.thinlto_codegen_set_savetemps_dir$FUNC
    );
    static final FunctionDescriptor thinlto_set_generated_objects_dir$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle thinlto_set_generated_objects_dir$MH = RuntimeHelper.downcallHandle(
        "thinlto_set_generated_objects_dir",
        constants$282.thinlto_set_generated_objects_dir$FUNC
    );
}


