// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$127 {

    static final FunctionDescriptor LLVMConstRealOfString$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstRealOfString$MH = RuntimeHelper.downcallHandle(
        "LLVMConstRealOfString",
        constants$127.LLVMConstRealOfString$FUNC
    );
    static final FunctionDescriptor LLVMConstRealOfStringAndSize$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMConstRealOfStringAndSize$MH = RuntimeHelper.downcallHandle(
        "LLVMConstRealOfStringAndSize",
        constants$127.LLVMConstRealOfStringAndSize$FUNC
    );
    static final FunctionDescriptor LLVMConstIntGetZExtValue$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstIntGetZExtValue$MH = RuntimeHelper.downcallHandle(
        "LLVMConstIntGetZExtValue",
        constants$127.LLVMConstIntGetZExtValue$FUNC
    );
    static final FunctionDescriptor LLVMConstIntGetSExtValue$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstIntGetSExtValue$MH = RuntimeHelper.downcallHandle(
        "LLVMConstIntGetSExtValue",
        constants$127.LLVMConstIntGetSExtValue$FUNC
    );
    static final FunctionDescriptor LLVMConstRealGetDouble$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMConstRealGetDouble$MH = RuntimeHelper.downcallHandle(
        "LLVMConstRealGetDouble",
        constants$127.LLVMConstRealGetDouble$FUNC
    );
    static final FunctionDescriptor LLVMConstStringInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMConstStringInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMConstStringInContext",
        constants$127.LLVMConstStringInContext$FUNC
    );
}


