// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$37 {

    static final FunctionDescriptor LLVMGetSectionName$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetSectionName$MH = RuntimeHelper.downcallHandle(
        "LLVMGetSectionName",
        constants$37.LLVMGetSectionName$FUNC
    );
    static final FunctionDescriptor LLVMGetSectionSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetSectionSize$MH = RuntimeHelper.downcallHandle(
        "LLVMGetSectionSize",
        constants$37.LLVMGetSectionSize$FUNC
    );
    static final FunctionDescriptor LLVMGetSectionContents$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetSectionContents$MH = RuntimeHelper.downcallHandle(
        "LLVMGetSectionContents",
        constants$37.LLVMGetSectionContents$FUNC
    );
    static final FunctionDescriptor LLVMGetSectionAddress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetSectionAddress$MH = RuntimeHelper.downcallHandle(
        "LLVMGetSectionAddress",
        constants$37.LLVMGetSectionAddress$FUNC
    );
    static final FunctionDescriptor LLVMGetSectionContainsSymbol$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetSectionContainsSymbol$MH = RuntimeHelper.downcallHandle(
        "LLVMGetSectionContainsSymbol",
        constants$37.LLVMGetSectionContainsSymbol$FUNC
    );
    static final FunctionDescriptor LLVMGetRelocations$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetRelocations$MH = RuntimeHelper.downcallHandle(
        "LLVMGetRelocations",
        constants$37.LLVMGetRelocations$FUNC
    );
}


