// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$115 {

    static final FunctionDescriptor LLVMIsAFCmpInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAFCmpInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAFCmpInst",
        constants$115.LLVMIsAFCmpInst$FUNC
    );
    static final FunctionDescriptor LLVMIsAICmpInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAICmpInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAICmpInst",
        constants$115.LLVMIsAICmpInst$FUNC
    );
    static final FunctionDescriptor LLVMIsAExtractElementInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAExtractElementInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAExtractElementInst",
        constants$115.LLVMIsAExtractElementInst$FUNC
    );
    static final FunctionDescriptor LLVMIsAGetElementPtrInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAGetElementPtrInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAGetElementPtrInst",
        constants$115.LLVMIsAGetElementPtrInst$FUNC
    );
    static final FunctionDescriptor LLVMIsAInsertElementInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAInsertElementInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAInsertElementInst",
        constants$115.LLVMIsAInsertElementInst$FUNC
    );
    static final FunctionDescriptor LLVMIsAInsertValueInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsAInsertValueInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsAInsertValueInst",
        constants$115.LLVMIsAInsertValueInst$FUNC
    );
}


