// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$23 {

    static final FunctionDescriptor mlirValueIsABlockArgument$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirValue")
    );
    static final MethodHandle mlirValueIsABlockArgument$MH = RuntimeHelper.downcallHandle(
        "mlirValueIsABlockArgument",
        constants$23.mlirValueIsABlockArgument$FUNC
    );
    static final FunctionDescriptor mlirValueIsAOpResult$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirValue")
    );
    static final MethodHandle mlirValueIsAOpResult$MH = RuntimeHelper.downcallHandle(
        "mlirValueIsAOpResult",
        constants$23.mlirValueIsAOpResult$FUNC
    );
    static final FunctionDescriptor mlirBlockArgumentGetOwner$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirBlock"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirValue")
    );
    static final MethodHandle mlirBlockArgumentGetOwner$MH = RuntimeHelper.downcallHandle(
        "mlirBlockArgumentGetOwner",
        constants$23.mlirBlockArgumentGetOwner$FUNC
    );
    static final FunctionDescriptor mlirBlockArgumentGetArgNumber$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirValue")
    );
    static final MethodHandle mlirBlockArgumentGetArgNumber$MH = RuntimeHelper.downcallHandle(
        "mlirBlockArgumentGetArgNumber",
        constants$23.mlirBlockArgumentGetArgNumber$FUNC
    );
    static final FunctionDescriptor mlirBlockArgumentSetType$FUNC = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirValue"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType")
    );
    static final MethodHandle mlirBlockArgumentSetType$MH = RuntimeHelper.downcallHandle(
        "mlirBlockArgumentSetType",
        constants$23.mlirBlockArgumentSetType$FUNC
    );
    static final FunctionDescriptor mlirOpResultGetOwner$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirOperation"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirValue")
    );
    static final MethodHandle mlirOpResultGetOwner$MH = RuntimeHelper.downcallHandle(
        "mlirOpResultGetOwner",
        constants$23.mlirOpResultGetOwner$FUNC
    );
}


