// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$281 {

    static final FunctionDescriptor lto_runtime_lib_symbols_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_runtime_lib_symbols_list$MH = RuntimeHelper.downcallHandle(
        "lto_runtime_lib_symbols_list",
        constants$281.lto_runtime_lib_symbols_list$FUNC
    );
    static final FunctionDescriptor thinlto_create_codegen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle thinlto_create_codegen$MH = RuntimeHelper.downcallHandle(
        "thinlto_create_codegen",
        constants$281.thinlto_create_codegen$FUNC
    );
    static final FunctionDescriptor thinlto_codegen_dispose$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle thinlto_codegen_dispose$MH = RuntimeHelper.downcallHandle(
        "thinlto_codegen_dispose",
        constants$281.thinlto_codegen_dispose$FUNC
    );
    static final FunctionDescriptor thinlto_codegen_add_module$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle thinlto_codegen_add_module$MH = RuntimeHelper.downcallHandle(
        "thinlto_codegen_add_module",
        constants$281.thinlto_codegen_add_module$FUNC
    );
    static final FunctionDescriptor thinlto_codegen_process$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle thinlto_codegen_process$MH = RuntimeHelper.downcallHandle(
        "thinlto_codegen_process",
        constants$281.thinlto_codegen_process$FUNC
    );
    static final FunctionDescriptor thinlto_module_get_num_objects$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle thinlto_module_get_num_objects$MH = RuntimeHelper.downcallHandle(
        "thinlto_module_get_num_objects",
        constants$281.thinlto_module_get_num_objects$FUNC
    );
}


