// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$177 {

    static final FunctionDescriptor LLVMBuildNUWAdd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildNUWAdd$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildNUWAdd",
        constants$177.LLVMBuildNUWAdd$FUNC
    );
    static final FunctionDescriptor LLVMBuildFAdd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildFAdd$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildFAdd",
        constants$177.LLVMBuildFAdd$FUNC
    );
    static final FunctionDescriptor LLVMBuildSub$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildSub$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildSub",
        constants$177.LLVMBuildSub$FUNC
    );
    static final FunctionDescriptor LLVMBuildNSWSub$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildNSWSub$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildNSWSub",
        constants$177.LLVMBuildNSWSub$FUNC
    );
    static final FunctionDescriptor LLVMBuildNUWSub$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildNUWSub$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildNUWSub",
        constants$177.LLVMBuildNUWSub$FUNC
    );
    static final FunctionDescriptor LLVMBuildFSub$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildFSub$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildFSub",
        constants$177.LLVMBuildFSub$FUNC
    );
}


