// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$82 {

    static final FunctionDescriptor LLVMContextGetDiagnosticContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMContextGetDiagnosticContext$MH = RuntimeHelper.downcallHandle(
        "LLVMContextGetDiagnosticContext",
        constants$82.LLVMContextGetDiagnosticContext$FUNC
    );
    static final FunctionDescriptor LLVMContextSetYieldCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMContextSetYieldCallback$MH = RuntimeHelper.downcallHandle(
        "LLVMContextSetYieldCallback",
        constants$82.LLVMContextSetYieldCallback$FUNC
    );
    static final FunctionDescriptor LLVMContextShouldDiscardValueNames$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMContextShouldDiscardValueNames$MH = RuntimeHelper.downcallHandle(
        "LLVMContextShouldDiscardValueNames",
        constants$82.LLVMContextShouldDiscardValueNames$FUNC
    );
    static final FunctionDescriptor LLVMContextSetDiscardValueNames$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMContextSetDiscardValueNames$MH = RuntimeHelper.downcallHandle(
        "LLVMContextSetDiscardValueNames",
        constants$82.LLVMContextSetDiscardValueNames$FUNC
    );
    static final FunctionDescriptor LLVMContextDispose$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMContextDispose$MH = RuntimeHelper.downcallHandle(
        "LLVMContextDispose",
        constants$82.LLVMContextDispose$FUNC
    );
    static final FunctionDescriptor LLVMGetDiagInfoDescription$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetDiagInfoDescription$MH = RuntimeHelper.downcallHandle(
        "LLVMGetDiagInfoDescription",
        constants$82.LLVMGetDiagInfoDescription$FUNC
    );
}


