// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$218 {

    static final FunctionDescriptor LLVMOrcIRTransformLayerSetTransform$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcIRTransformLayerSetTransform$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcIRTransformLayerSetTransform",
        constants$218.LLVMOrcIRTransformLayerSetTransform$FUNC
    );
    static final FunctionDescriptor LLVMOrcObjectTransformLayerSetTransform$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcObjectTransformLayerSetTransform$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcObjectTransformLayerSetTransform",
        constants$218.LLVMOrcObjectTransformLayerSetTransform$FUNC
    );
    static final FunctionDescriptor LLVMOrcCreateLocalIndirectStubsManager$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcCreateLocalIndirectStubsManager$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcCreateLocalIndirectStubsManager",
        constants$218.LLVMOrcCreateLocalIndirectStubsManager$FUNC
    );
    static final FunctionDescriptor LLVMOrcDisposeIndirectStubsManager$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcDisposeIndirectStubsManager$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcDisposeIndirectStubsManager",
        constants$218.LLVMOrcDisposeIndirectStubsManager$FUNC
    );
    static final FunctionDescriptor LLVMOrcCreateLocalLazyCallThroughManager$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcCreateLocalLazyCallThroughManager$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcCreateLocalLazyCallThroughManager",
        constants$218.LLVMOrcCreateLocalLazyCallThroughManager$FUNC
    );
    static final FunctionDescriptor LLVMOrcDisposeLazyCallThroughManager$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcDisposeLazyCallThroughManager$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcDisposeLazyCallThroughManager",
        constants$218.LLVMOrcDisposeLazyCallThroughManager$FUNC
    );
}


