// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$84 {

    static final FunctionDescriptor LLVMGetEnumAttributeKind$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetEnumAttributeKind$MH = RuntimeHelper.downcallHandle(
        "LLVMGetEnumAttributeKind",
        constants$84.LLVMGetEnumAttributeKind$FUNC
    );
    static final FunctionDescriptor LLVMGetEnumAttributeValue$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetEnumAttributeValue$MH = RuntimeHelper.downcallHandle(
        "LLVMGetEnumAttributeValue",
        constants$84.LLVMGetEnumAttributeValue$FUNC
    );
    static final FunctionDescriptor LLVMCreateTypeAttribute$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMCreateTypeAttribute$MH = RuntimeHelper.downcallHandle(
        "LLVMCreateTypeAttribute",
        constants$84.LLVMCreateTypeAttribute$FUNC
    );
    static final FunctionDescriptor LLVMGetTypeAttributeValue$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetTypeAttributeValue$MH = RuntimeHelper.downcallHandle(
        "LLVMGetTypeAttributeValue",
        constants$84.LLVMGetTypeAttributeValue$FUNC
    );
    static final FunctionDescriptor LLVMCreateStringAttribute$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMCreateStringAttribute$MH = RuntimeHelper.downcallHandle(
        "LLVMCreateStringAttribute",
        constants$84.LLVMCreateStringAttribute$FUNC
    );
    static final FunctionDescriptor LLVMGetStringAttributeKind$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetStringAttributeKind$MH = RuntimeHelper.downcallHandle(
        "LLVMGetStringAttributeKind",
        constants$84.LLVMGetStringAttributeKind$FUNC
    );
}


