// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$212 {

    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityNotifyEmitted$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityNotifyEmitted$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityNotifyEmitted",
        constants$212.LLVMOrcMaterializationResponsibilityNotifyEmitted$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityDefineMaterializing$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityDefineMaterializing$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityDefineMaterializing",
        constants$212.LLVMOrcMaterializationResponsibilityDefineMaterializing$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityFailMaterialization$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityFailMaterialization$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityFailMaterialization",
        constants$212.LLVMOrcMaterializationResponsibilityFailMaterialization$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityReplace$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityReplace$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityReplace",
        constants$212.LLVMOrcMaterializationResponsibilityReplace$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityDelegate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityDelegate$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityDelegate",
        constants$212.LLVMOrcMaterializationResponsibilityDelegate$FUNC
    );
    static final FunctionDescriptor LLVMOrcMaterializationResponsibilityAddDependencies$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LLVMOrcMaterializationResponsibilityAddDependencies$MH = RuntimeHelper.downcallHandle(
        "LLVMOrcMaterializationResponsibilityAddDependencies",
        constants$212.LLVMOrcMaterializationResponsibilityAddDependencies$FUNC
    );
}


