// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$342 {

    static final FunctionDescriptor mlirAttributeIsADenseI64Array$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirAttribute")
    );
    static final MethodHandle mlirAttributeIsADenseI64Array$MH = RuntimeHelper.downcallHandle(
        "mlirAttributeIsADenseI64Array",
        constants$342.mlirAttributeIsADenseI64Array$FUNC
    );
    static final FunctionDescriptor mlirAttributeIsADenseF32Array$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirAttribute")
    );
    static final MethodHandle mlirAttributeIsADenseF32Array$MH = RuntimeHelper.downcallHandle(
        "mlirAttributeIsADenseF32Array",
        constants$342.mlirAttributeIsADenseF32Array$FUNC
    );
    static final FunctionDescriptor mlirAttributeIsADenseF64Array$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirAttribute")
    );
    static final MethodHandle mlirAttributeIsADenseF64Array$MH = RuntimeHelper.downcallHandle(
        "mlirAttributeIsADenseF64Array",
        constants$342.mlirAttributeIsADenseF64Array$FUNC
    );
    static final FunctionDescriptor mlirDenseBoolArrayGet$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirContext"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseBoolArrayGet$MH = RuntimeHelper.downcallHandle(
        "mlirDenseBoolArrayGet",
        constants$342.mlirDenseBoolArrayGet$FUNC
    );
    static final FunctionDescriptor mlirDenseI8ArrayGet$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirContext"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseI8ArrayGet$MH = RuntimeHelper.downcallHandle(
        "mlirDenseI8ArrayGet",
        constants$342.mlirDenseI8ArrayGet$FUNC
    );
    static final FunctionDescriptor mlirDenseI16ArrayGet$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirContext"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseI16ArrayGet$MH = RuntimeHelper.downcallHandle(
        "mlirDenseI16ArrayGet",
        constants$342.mlirDenseI16ArrayGet$FUNC
    );
}


