// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$348 {

    static final FunctionDescriptor mlirDenseElementsAttrUInt16Get$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseElementsAttrUInt16Get$MH = RuntimeHelper.downcallHandle(
        "mlirDenseElementsAttrUInt16Get",
        constants$348.mlirDenseElementsAttrUInt16Get$FUNC
    );
    static final FunctionDescriptor mlirDenseElementsAttrInt16Get$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseElementsAttrInt16Get$MH = RuntimeHelper.downcallHandle(
        "mlirDenseElementsAttrInt16Get",
        constants$348.mlirDenseElementsAttrInt16Get$FUNC
    );
    static final FunctionDescriptor mlirDenseElementsAttrUInt32Get$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseElementsAttrUInt32Get$MH = RuntimeHelper.downcallHandle(
        "mlirDenseElementsAttrUInt32Get",
        constants$348.mlirDenseElementsAttrUInt32Get$FUNC
    );
    static final FunctionDescriptor mlirDenseElementsAttrInt32Get$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseElementsAttrInt32Get$MH = RuntimeHelper.downcallHandle(
        "mlirDenseElementsAttrInt32Get",
        constants$348.mlirDenseElementsAttrInt32Get$FUNC
    );
    static final FunctionDescriptor mlirDenseElementsAttrUInt64Get$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseElementsAttrUInt64Get$MH = RuntimeHelper.downcallHandle(
        "mlirDenseElementsAttrUInt64Get",
        constants$348.mlirDenseElementsAttrUInt64Get$FUNC
    );
    static final FunctionDescriptor mlirDenseElementsAttrInt64Get$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("ptr")
    ).withName("MlirAttribute"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ptr")
        ).withName("MlirType"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mlirDenseElementsAttrInt64Get$MH = RuntimeHelper.downcallHandle(
        "mlirDenseElementsAttrInt64Get",
        constants$348.mlirDenseElementsAttrInt64Get$FUNC
    );
}


