// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$184 {

    static final FunctionDescriptor LLVMBuildStructGEP2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildStructGEP2$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildStructGEP2",
        constants$184.LLVMBuildStructGEP2$FUNC
    );
    static final FunctionDescriptor LLVMBuildGlobalString$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildGlobalString$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildGlobalString",
        constants$184.LLVMBuildGlobalString$FUNC
    );
    static final FunctionDescriptor LLVMBuildGlobalStringPtr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMBuildGlobalStringPtr$MH = RuntimeHelper.downcallHandle(
        "LLVMBuildGlobalStringPtr",
        constants$184.LLVMBuildGlobalStringPtr$FUNC
    );
    static final FunctionDescriptor LLVMGetVolatile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetVolatile$MH = RuntimeHelper.downcallHandle(
        "LLVMGetVolatile",
        constants$184.LLVMGetVolatile$FUNC
    );
    static final FunctionDescriptor LLVMSetVolatile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMSetVolatile$MH = RuntimeHelper.downcallHandle(
        "LLVMSetVolatile",
        constants$184.LLVMSetVolatile$FUNC
    );
    static final FunctionDescriptor LLVMGetWeak$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetWeak$MH = RuntimeHelper.downcallHandle(
        "LLVMGetWeak",
        constants$184.LLVMGetWeak$FUNC
    );
}


