// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$277 {

    static final FunctionDescriptor lto_codegen_add_module$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_add_module$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_add_module",
        constants$277.lto_codegen_add_module$FUNC
    );
    static final FunctionDescriptor lto_codegen_set_module$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_set_module$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_set_module",
        constants$277.lto_codegen_set_module$FUNC
    );
    static final FunctionDescriptor lto_codegen_set_debug_model$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle lto_codegen_set_debug_model$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_set_debug_model",
        constants$277.lto_codegen_set_debug_model$FUNC
    );
    static final FunctionDescriptor lto_codegen_set_pic_model$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle lto_codegen_set_pic_model$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_set_pic_model",
        constants$277.lto_codegen_set_pic_model$FUNC
    );
    static final FunctionDescriptor lto_codegen_set_cpu$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_set_cpu$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_set_cpu",
        constants$277.lto_codegen_set_cpu$FUNC
    );
    static final FunctionDescriptor lto_codegen_set_assembler_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_codegen_set_assembler_path$MH = RuntimeHelper.downcallHandle(
        "lto_codegen_set_assembler_path",
        constants$277.lto_codegen_set_assembler_path$FUNC
    );
}


