// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$162 {

    static final FunctionDescriptor LLVMGetICmpPredicate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetICmpPredicate$MH = RuntimeHelper.downcallHandle(
        "LLVMGetICmpPredicate",
        constants$162.LLVMGetICmpPredicate$FUNC
    );
    static final FunctionDescriptor LLVMGetFCmpPredicate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetFCmpPredicate$MH = RuntimeHelper.downcallHandle(
        "LLVMGetFCmpPredicate",
        constants$162.LLVMGetFCmpPredicate$FUNC
    );
    static final FunctionDescriptor LLVMInstructionClone$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMInstructionClone$MH = RuntimeHelper.downcallHandle(
        "LLVMInstructionClone",
        constants$162.LLVMInstructionClone$FUNC
    );
    static final FunctionDescriptor LLVMIsATerminatorInst$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMIsATerminatorInst$MH = RuntimeHelper.downcallHandle(
        "LLVMIsATerminatorInst",
        constants$162.LLVMIsATerminatorInst$FUNC
    );
    static final FunctionDescriptor LLVMGetNumArgOperands$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMGetNumArgOperands$MH = RuntimeHelper.downcallHandle(
        "LLVMGetNumArgOperands",
        constants$162.LLVMGetNumArgOperands$FUNC
    );
    static final FunctionDescriptor LLVMSetInstructionCallConv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle LLVMSetInstructionCallConv$MH = RuntimeHelper.downcallHandle(
        "LLVMSetInstructionCallConv",
        constants$162.LLVMSetInstructionCallConv$FUNC
    );
}


