// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$75 {

    static final FunctionDescriptor LLVMFatalErrorHandler$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMFatalErrorHandler$MH = RuntimeHelper.downcallHandle(
        constants$75.LLVMFatalErrorHandler$FUNC
    );
    static final FunctionDescriptor LLVMInstallFatalErrorHandler$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMInstallFatalErrorHandler$MH = RuntimeHelper.downcallHandle(
        "LLVMInstallFatalErrorHandler",
        constants$75.LLVMInstallFatalErrorHandler$FUNC
    );
    static final FunctionDescriptor LLVMResetFatalErrorHandler$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle LLVMResetFatalErrorHandler$MH = RuntimeHelper.downcallHandle(
        "LLVMResetFatalErrorHandler",
        constants$75.LLVMResetFatalErrorHandler$FUNC
    );
    static final FunctionDescriptor LLVMEnablePrettyStackTrace$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle LLVMEnablePrettyStackTrace$MH = RuntimeHelper.downcallHandle(
        "LLVMEnablePrettyStackTrace",
        constants$75.LLVMEnablePrettyStackTrace$FUNC
    );
    static final FunctionDescriptor LLVMRemarkStringGetData$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMRemarkStringGetData$MH = RuntimeHelper.downcallHandle(
        "LLVMRemarkStringGetData",
        constants$75.LLVMRemarkStringGetData$FUNC
    );
    static final FunctionDescriptor LLVMRemarkStringGetLen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMRemarkStringGetLen$MH = RuntimeHelper.downcallHandle(
        "LLVMRemarkStringGetLen",
        constants$75.LLVMRemarkStringGetLen$FUNC
    );
}


