// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$158 {

    static final FunctionDescriptor LLVMInsertExistingBasicBlockAfterInsertBlock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMInsertExistingBasicBlockAfterInsertBlock$MH = RuntimeHelper.downcallHandle(
        "LLVMInsertExistingBasicBlockAfterInsertBlock",
        constants$158.LLVMInsertExistingBasicBlockAfterInsertBlock$FUNC
    );
    static final FunctionDescriptor LLVMAppendExistingBasicBlock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAppendExistingBasicBlock$MH = RuntimeHelper.downcallHandle(
        "LLVMAppendExistingBasicBlock",
        constants$158.LLVMAppendExistingBasicBlock$FUNC
    );
    static final FunctionDescriptor LLVMCreateBasicBlockInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMCreateBasicBlockInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMCreateBasicBlockInContext",
        constants$158.LLVMCreateBasicBlockInContext$FUNC
    );
    static final FunctionDescriptor LLVMAppendBasicBlockInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAppendBasicBlockInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMAppendBasicBlockInContext",
        constants$158.LLVMAppendBasicBlockInContext$FUNC
    );
    static final FunctionDescriptor LLVMAppendBasicBlock$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMAppendBasicBlock$MH = RuntimeHelper.downcallHandle(
        "LLVMAppendBasicBlock",
        constants$158.LLVMAppendBasicBlock$FUNC
    );
    static final FunctionDescriptor LLVMInsertBasicBlockInContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LLVMInsertBasicBlockInContext$MH = RuntimeHelper.downcallHandle(
        "LLVMInsertBasicBlockInContext",
        constants$158.LLVMInsertBasicBlockInContext$FUNC
    );
}


