// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$273 {

    static final FunctionDescriptor lto_module_is_object_file_in_memory$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle lto_module_is_object_file_in_memory$MH = RuntimeHelper.downcallHandle(
        "lto_module_is_object_file_in_memory",
        constants$273.lto_module_is_object_file_in_memory$FUNC
    );
    static final FunctionDescriptor lto_module_is_object_file_in_memory_for_target$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_is_object_file_in_memory_for_target$MH = RuntimeHelper.downcallHandle(
        "lto_module_is_object_file_in_memory_for_target",
        constants$273.lto_module_is_object_file_in_memory_for_target$FUNC
    );
    static final FunctionDescriptor lto_module_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_create$MH = RuntimeHelper.downcallHandle(
        "lto_module_create",
        constants$273.lto_module_create$FUNC
    );
    static final FunctionDescriptor lto_module_create_from_memory$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle lto_module_create_from_memory$MH = RuntimeHelper.downcallHandle(
        "lto_module_create_from_memory",
        constants$273.lto_module_create_from_memory$FUNC
    );
    static final FunctionDescriptor lto_module_create_from_memory_with_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_create_from_memory_with_path$MH = RuntimeHelper.downcallHandle(
        "lto_module_create_from_memory_with_path",
        constants$273.lto_module_create_from_memory_with_path$FUNC
    );
    static final FunctionDescriptor lto_module_create_in_local_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lto_module_create_in_local_context$MH = RuntimeHelper.downcallHandle(
        "lto_module_create_in_local_context",
        constants$273.lto_module_create_in_local_context$FUNC
    );
}


