// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class LLVMOpInfoSymbol1 {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("Present"),
        Constants$root.C_POINTER$LAYOUT.withName("Name"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("Value")
    ).withName("LLVMOpInfoSymbol1");
    public static MemoryLayout $LAYOUT() {
        return LLVMOpInfoSymbol1.$struct$LAYOUT;
    }
    static final VarHandle Present$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Present"));
    public static VarHandle Present$VH() {
        return LLVMOpInfoSymbol1.Present$VH;
    }
    public static long Present$get(MemorySegment seg) {
        return (long)LLVMOpInfoSymbol1.Present$VH.get(seg);
    }
    public static void Present$set( MemorySegment seg, long x) {
        LLVMOpInfoSymbol1.Present$VH.set(seg, x);
    }
    public static long Present$get(MemorySegment seg, long index) {
        return (long)LLVMOpInfoSymbol1.Present$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Present$set(MemorySegment seg, long index, long x) {
        LLVMOpInfoSymbol1.Present$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle Name$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Name"));
    public static VarHandle Name$VH() {
        return LLVMOpInfoSymbol1.Name$VH;
    }
    public static MemoryAddress Name$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)LLVMOpInfoSymbol1.Name$VH.get(seg);
    }
    public static void Name$set( MemorySegment seg, MemoryAddress x) {
        LLVMOpInfoSymbol1.Name$VH.set(seg, x);
    }
    public static MemoryAddress Name$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)LLVMOpInfoSymbol1.Name$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Name$set(MemorySegment seg, long index, MemoryAddress x) {
        LLVMOpInfoSymbol1.Name$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle Value$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Value"));
    public static VarHandle Value$VH() {
        return LLVMOpInfoSymbol1.Value$VH;
    }
    public static long Value$get(MemorySegment seg) {
        return (long)LLVMOpInfoSymbol1.Value$VH.get(seg);
    }
    public static void Value$set( MemorySegment seg, long x) {
        LLVMOpInfoSymbol1.Value$VH.set(seg, x);
    }
    public static long Value$get(MemorySegment seg, long index) {
        return (long)LLVMOpInfoSymbol1.Value$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Value$set(MemorySegment seg, long index, long x) {
        LLVMOpInfoSymbol1.Value$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


