// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface LLVMOrcObjectTransformLayerTransformFunction {

    java.lang.foreign.Addressable apply(java.lang.foreign.MemoryAddress Ctx, java.lang.foreign.MemoryAddress ObjInOut);
    static MemorySegment allocate(LLVMOrcObjectTransformLayerTransformFunction fi, MemorySession session) {
        return RuntimeHelper.upcallStub(LLVMOrcObjectTransformLayerTransformFunction.class, fi, constants$207.LLVMOrcObjectTransformLayerTransformFunction$FUNC, session);
    }
    static LLVMOrcObjectTransformLayerTransformFunction ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _Ctx, java.lang.foreign.MemoryAddress _ObjInOut) -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$207.LLVMOrcObjectTransformLayerTransformFunction$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_Ctx, (java.lang.foreign.Addressable)_ObjInOut);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


