// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface LLVMMemoryManagerNotifyTerminatingCallback {

    void apply(java.lang.foreign.MemoryAddress CtxCtx);
    static MemorySegment allocate(LLVMMemoryManagerNotifyTerminatingCallback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(LLVMMemoryManagerNotifyTerminatingCallback.class, fi, constants$262.LLVMMemoryManagerNotifyTerminatingCallback$FUNC, session);
    }
    static LLVMMemoryManagerNotifyTerminatingCallback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _CtxCtx) -> {
            try {
                constants$262.LLVMMemoryManagerNotifyTerminatingCallback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_CtxCtx);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


