// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface LLVMOrcErrorReporterFunction {

    void apply(java.lang.foreign.MemoryAddress Ctx, java.lang.foreign.MemoryAddress Err);
    static MemorySegment allocate(LLVMOrcErrorReporterFunction fi, MemorySession session) {
        return RuntimeHelper.upcallStub(LLVMOrcErrorReporterFunction.class, fi, constants$204.LLVMOrcErrorReporterFunction$FUNC, session);
    }
    static LLVMOrcErrorReporterFunction ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _Ctx, java.lang.foreign.MemoryAddress _Err) -> {
            try {
                constants$204.LLVMOrcErrorReporterFunction$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_Ctx, (java.lang.foreign.Addressable)_Err);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


