// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface LLVMOrcSymbolPredicate {

    int apply(java.lang.foreign.MemoryAddress Ctx, java.lang.foreign.MemoryAddress Sym);
    static MemorySegment allocate(LLVMOrcSymbolPredicate fi, MemorySession session) {
        return RuntimeHelper.upcallStub(LLVMOrcSymbolPredicate.class, fi, constants$206.LLVMOrcSymbolPredicate$FUNC, session);
    }
    static LLVMOrcSymbolPredicate ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _Ctx, java.lang.foreign.MemoryAddress _Sym) -> {
            try {
                return (int)constants$206.LLVMOrcSymbolPredicate$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_Ctx, (java.lang.foreign.Addressable)_Sym);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


