// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface LLVMMemoryManagerAllocateDataSectionCallback {

    java.lang.foreign.Addressable apply(java.lang.foreign.MemoryAddress Opaque, long Size, int Alignment, int SectionID, java.lang.foreign.MemoryAddress SectionName, int IsReadOnly);
    static MemorySegment allocate(LLVMMemoryManagerAllocateDataSectionCallback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(LLVMMemoryManagerAllocateDataSectionCallback.class, fi, constants$260.LLVMMemoryManagerAllocateDataSectionCallback$FUNC, session);
    }
    static LLVMMemoryManagerAllocateDataSectionCallback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _Opaque, long _Size, int _Alignment, int _SectionID, java.lang.foreign.MemoryAddress _SectionName, int _IsReadOnly) -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$260.LLVMMemoryManagerAllocateDataSectionCallback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_Opaque, _Size, _Alignment, _SectionID, (java.lang.foreign.Addressable)_SectionName, _IsReadOnly);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


