// Generated by jextract

package org.mlir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction {

    java.lang.foreign.Addressable apply(java.lang.foreign.MemoryAddress Ctx, java.lang.foreign.MemoryAddress ES, java.lang.foreign.MemoryAddress Triple);
    static MemorySegment allocate(LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction fi, MemorySession session) {
        return RuntimeHelper.upcallStub(LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction.class, fi, constants$219.LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction$FUNC, session);
    }
    static LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _Ctx, java.lang.foreign.MemoryAddress _ES, java.lang.foreign.MemoryAddress _Triple) -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$219.LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_Ctx, (java.lang.foreign.Addressable)_ES, (java.lang.foreign.Addressable)_Triple);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


